function getData(){
	const keysw = "www.aztoptseller.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B000058TJ3: {href: "https://amzn.to/34QWrnO",nameProduct: `Intex Swim Center Family Inflatable Pool`,image: '',summary: ``,slug: ""},
			B00005RHPD: {href: "https://amzn.to/3uNDwVq",nameProduct: `Bosch 1617EVSPK Wood Router Tool Combo Kit`,image: '',summary: ``,slug: ""},
			B000092TT0: {href: "https://amzn.to/34NtDwr",nameProduct: `Polk Audio PSW505 12" Powered`,image: '',summary: ``,slug: ""},
			B0000AMK5F: {href: "https://amzn.to/3z6cThG",nameProduct: `BOSTITCH Coil Roofing Nailer`,image: '',summary: ``,slug: ""},
			B0002KVQBA: {href: "https://amzn.to/34Of7nU",nameProduct: `Polk Audio PSW10 10" Powered Subwoofer`,image: '',summary: ``,slug: ""},
			B000ANEPYO: {href: "https://amzn.to/3iwLkIP",nameProduct: `Honeywell HFD-120-Q `,image: '',summary: ``,slug: ""},
			B000BO8AKW: {href: "https://amzn.to/3ciO60j",nameProduct: `Butterfly Centrefold 25 Table Tennis Table`,image: '',summary: ``,slug: ""},
			B000GFPTQY: {href: "https://amzn.to/3chLn78",nameProduct: `Bose Acoutimass 10 Series IV`,image: '',summary: ``,slug: ""},
			B000UXPFMU: {href: "https://amzn.to/2SY4I6K",nameProduct: `Pentair SuperFlo Pool Pump`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/3pofmQ3",nameProduct: `DuroMax XP4400E Generator`,image: '',summary: ``,slug: ""},
			B002635ODW: {href: "https://amzn.to/3g6q75s",nameProduct: `EcoSmart ECO 27 Electric Tankless Water Heater`,image: '',summary: ``,slug: ""},
			B002G51BZU: {href: "https://amzn.to/3uOH5KR",nameProduct: `Mr. Heater Portable Buddy Heater`,image: '',summary: ``,slug: ""},
			B002QAYJPO: {href: "https://amzn.to/3uTbVSL",nameProduct: `Honeywell Germ Free Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B002R8CPRY: {href: "https://amzn.to/353zuhn",nameProduct: `Sunny Health and Fitness SF E905 Elliptical Machine Cross Trainer `,image: '',summary: ``,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3cjXJvL",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System`,image: '',summary: ``,slug: ""},
			B003MANSNG: {href: "https://amzn.to/3z4M915",nameProduct: `National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B0043E6PLC: {href: "https://amzn.to/3fVkyYS",nameProduct: `BLACK+DECKER Countertop Convection Toaster Oven`,image: '',summary: ``,slug: ""},
			B00467H5YW: {href: "https://amzn.to/34PfrD5",nameProduct: `Sunny Health & Fitness Exercise Cycling Bike`,image: '',summary: ``,slug: ""},
			B004PULVOK: {href: "https://amzn.to/3fR2xKY",nameProduct: `Kohler K-3999-0 Highline Comfort Height `,image: '',summary: ``,slug: ""},
			B004QERFA4: {href: "https://amzn.to/3zdbTIX",nameProduct: `Kohler Santa Rosa Comfort Toilet Review`,image: '',summary: ``,slug: ""},
			B0052OX876: {href: "https://amzn.to/3inaw4a",nameProduct: `Lotos LTP5000D 50Amp Non-Touch Pilot Arc Plasma Cutter`,image: '',summary: ``,slug: ""},
			B0055P70MQ: {href: "https://amzn.to/34OfEGq",nameProduct: `Technivorm Moccamaster 59616 KBG Coffee Brewer`,image: '',summary: ``,slug: ""},
			B005BPWN0O: {href: "https://amzn.to/3vW3E1N",nameProduct: `Husqvarna 125B Handheld Blower`,image: '',summary: ``,slug: ""},
			B006H1QYBA: {href: "https://amzn.to/2SUfY3T",nameProduct: `Steelcase Leap Chair`,image: '',summary: ``,slug: ""},
			B006IY89ZA: {href: "https://amzn.to/3cjApy8",nameProduct: `Modway Articulate Ergonomic Mesh Office Chair`,image: '',summary: ``,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3ij6dqB",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B008DBRFBK: {href: "https://amzn.to/34OXbcX",nameProduct: `Bissell 3624 Spot Clean Professional`,image: '',summary: ``,slug: ""},
			B009IJ2LM4: {href: "https://amzn.to/3igfmjK",nameProduct: `TOTO Washlet s300e Electronic Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B009IJ2N9U: {href: "https://amzn.to/3uVj0lA",nameProduct: `TOTO Washlet s350e Review 2020`,image: '',summary: ``,slug: ""},
			B009SCPYN4: {href: "https://amzn.to/3x08cUK",nameProduct: `Hudson Bay Spas 4 Person`,image: '',summary: ``,slug: ""},
			B009X43F38: {href: "https://amzn.to/3z38tbw",nameProduct: `Hobart Handler 140 MIG Welder`,image: '',summary: ``,slug: ""},
			B00A8UPX0Y: {href: "https://amzn.to/3w6S9V2",nameProduct: `National Tree Company Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00AB24XIW: {href: "https://amzn.to/3vTqJ5e",nameProduct: `Dri-Eaz LGR 7000XLi Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00AB25016: {href: "https://amzn.to/3pnlOH6",nameProduct: `Dri-Eaz F284 DefendAir HEPA 500 Air Purifier`,image: '',summary: ``,slug: ""},
			B00BUV305A: {href: "https://amzn.to/3pmabQG",nameProduct: `Luraco i7 PLUS Medical Massage`,image: '',summary: ``,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/3uVa5Rp",nameProduct: `Flo by Moen Smart Water Shutoff `,image: '',summary: ``,slug: ""},
			B00CH9QWOU: {href: "https://amzn.to/34NuahZ",nameProduct: `Breville the Barista Express Espresso Machine`,image: '',summary: ``,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/3cg8QFO",nameProduct: `Touchstone 80001 Onyx Electric `,image: '',summary: ``,slug: ""},
			B00EPNDJ24: {href: "https://amzn.to/3z1UORX",nameProduct: `Manitowoc Nugget Ice Machine`,image: '',summary: ``,slug: ""},
			B00EUU5GFK: {href: "https://amzn.to/3uUdUGu",nameProduct: `Serta Ergonomic Executive Office Chair Review`,image: '',summary: ``,slug: ""},
			B00F2CGXGG: {href: "https://amzn.to/3clckH1",nameProduct: `Dewalt 10" DWE7491RS Table Saw with Rolling Stand Review`,image: '',summary: ``,slug: ""},
			B00FADLVAK: {href: "https://amzn.to/3fSViST",nameProduct: `Review National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00FH441AE: {href: "https://amzn.to/3pnsN2Q",nameProduct: `Review 16 Piece Deluxe Edition Christmas Nativity Set`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3z4kLjS",nameProduct: `TOTO MS992CUMFG#01 Neorest`,image: '',summary: ``,slug: ""},
			B00FT5VAWI: {href: "https://amzn.to/34LYd9I",nameProduct: `DeLonghi TRD40615T Full Room Radiant Heater Review`,image: '',summary: ``,slug: ""},
			B00G00BT72: {href: "https://amzn.to/3psmZFd",nameProduct: `McCulloch MC1375 Canister Steam Cleaner`,image: '',summary: ``,slug: ""},
			B00GBADAT6: {href: "https://amzn.to/34PUKa6",nameProduct: `JOOLA NOVA Outdoor Table Tennis`,image: '',summary: ``,slug: ""},
			B00GJ1N5VA: {href: "https://amzn.to/3wZ9TSx",nameProduct: `JOOLA Rally TL - Professional `,image: '',summary: ``,slug: ""},
			B00GN96JFW: {href: "https://amzn.to/3fSQwoi",nameProduct: `Flash Furniture Eclipse Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B00H3DIT14: {href: "https://amzn.to/3fSdk7O",nameProduct: `DRI EAZ F413 Revolution LGR Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00H3RI32U: {href: "https://amzn.to/353AFgN",nameProduct: `Touchstone 80004 - Sideline Electric Fireplace`,image: '',summary: ``,slug: ""},
			B00HRT863U: {href: "https://amzn.to/3fV1jhK",nameProduct: `Bestway SaluSpa Miami Inflatable Hot Tub`,image: '',summary: ``,slug: ""},
			B00HXGSBXC: {href: "https://amzn.to/3gbWQ9x",nameProduct: `RoyalBaby Kids Bike Boys Girls Freestyle Bicycle`,image: '',summary: ``,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/2SUgSgN",nameProduct: `APEC Drinking Water`,image: '',summary: ``,slug: ""},
			B00IFHPVEU: {href: "https://amzn.to/3x08Dym",nameProduct: `Amazon Basics Leather-Padded Office Chair Review`,image: '',summary: ``,slug: ""},
			B00IWJOOU8: {href: "https://amzn.to/3uTdaRV",nameProduct: `Briggs & Stratton P3000 Power Smart Series Inverter Generator`,image: '',summary: ``,slug: ""},
			B00JGRBSS6: {href: "https://amzn.to/3vUQli5",nameProduct: `Marcy 150-lb Multifunctional Home Gym Station`,image: '',summary: ``,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/3ck2LIi",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum`,image: '',summary: ``,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/34QBn0E",nameProduct: `Polaris F9550 Robotic Pool`,image: '',summary: ``,slug: ""},
			B00KYB47JU: {href: "https://amzn.to/3v2O8Qx",nameProduct: `American Spas AM-630LM 5-Person 30-Jet Lounger Spa`,image: '',summary: ``,slug: ""},
			B00LFS0DMG: {href: "https://amzn.to/2SbqOT8",nameProduct: `Steelcase Amia Task Chair Review`,image: '',summary: ``,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/2TDRGLL",nameProduct: `Hessaire MC37M Portable Evaporative Cooler`,image: '',summary: ``,slug: ""},
			B00NB3P98G: {href: "https://amzn.to/3fUwES4",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa`,image: '',summary: ``,slug: ""},
			B00OX5B8CW: {href: "https://amzn.to/3w77zsN",nameProduct: `Intex 12' x 30'' Metal Frame Pool`,image: '',summary: ``,slug: ""},
			B00PKXWIPC: {href: "https://amzn.to/3fQau34",nameProduct: `Review Safavieh Hudson Shag Collection SGH281A Area Rug`,image: '',summary: ``,slug: ""},
			B00Q7EE928: {href: "https://amzn.to/3preyu2",nameProduct: `Xspec 20 inch 7 Speed Folding Compact City Commuter Bike`,image: '',summary: ``,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3vTSScj",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B00Q7EPY04: {href: "https://amzn.to/3pnOK1A",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress Queen`,image: '',summary: ``,slug: ""},
			B00QBZ2BX2: {href: "https://amzn.to/3g7Zg9i",nameProduct: `TUFT & NEEDLE Original Mattress`,image: '',summary: ``,slug: ""},
			B00R6AW5S2: {href: "https://amzn.to/2TKKQUY",nameProduct: `Makita EB7650TH 75.6 cc MM4 Backpack Blower`,image: '',summary: ``,slug: ""},
			B00R73DYJW: {href: "https://amzn.to/3x2fKGv",nameProduct: `PuraFlame Western Electric Fireplace Insert`,image: '',summary: ``,slug: ""},
			B00R9HVPBK: {href: "https://amzn.to/3uUw4rq",nameProduct: `DHP Emily Futon Sofa Bed`,image: '',summary: ``,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/3pnOq2V",nameProduct: `WEN 56200i Super Quiet 2000 Watt Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B00TVFO08S: {href: "https://amzn.to/2T0YaUC",nameProduct: `Bose Acoustimass 6 Series V Home Theater Speaker System`,image: '',summary: ``,slug: ""},
			B00TVFO0B0: {href: "https://amzn.to/3uOmGG1",nameProduct: `Bose Acoustimass 10 series V`,image: '',summary: ``,slug: ""},
			B00UVAJU6O: {href: "https://amzn.to/3uNFO6Y",nameProduct: `Classic Brands Cool Ventilated Gel Memory Foam 10 Inch`,image: '',summary: ``,slug: ""},
			B00UWP07LK: {href: "https://amzn.to/3fTolFP",nameProduct: `Frigidaire 70-Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B00W4DCHUC: {href: "https://amzn.to/3gf1FPi",nameProduct: `Zinus Ibidun Upholstered Button Tufted Platform Bed`,image: '',summary: ``,slug: ""},
			B00WR1OTY8: {href: "https://amzn.to/3vTTdM7",nameProduct: `SVS Ultra Center Channel Loudspeaker`,image: '',summary: ``,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/3vVU6ns",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine`,image: '',summary: ``,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/2T1SpGw",nameProduct: `Review La-Z-Boy Delano Big`,image: '',summary: ``,slug: ""},
			B011IH6MBO: {href: "https://amzn.to/3fQnhCL",nameProduct: `Bose Wave SoundTouch Music System IV Review`,image: '',summary: ``,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3ppgbrO",nameProduct: `SmartBidet SB 1000 Smart Electric Bidet Seat`,image: '',summary: ``,slug: ""},
			B012H0K93I: {href: "https://amzn.to/3ppSa4g",nameProduct: `Zinus 12 Inch Cloud Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B013I40R8E: {href: "https://amzn.to/2S9S6ZW",nameProduct: `Breville BPR700BSS Fast Slow Pro Multi Function Cooker`,image: '',summary: ``,slug: ""},
			B013LIN5W2: {href: "https://amzn.to/3vYcwDZ",nameProduct: `Polk Audio T50 Home Theater Floor Standing Tower Speaker`,image: '',summary: ``,slug: ""},
			B0165UFOGS: {href: "https://amzn.to/3uUbyqX",nameProduct: `TOTO SW2014#01 A100 Electronic Bidet Toilet`,image: '',summary: ``,slug: ""},
			B016J0EITS: {href: "https://amzn.to/2TKL4vi",nameProduct: `SureFire X300 Ultra Series LED WeaponLights`,image: '',summary: ``,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/2T0YAKG",nameProduct: `Steelcase Gesture Chair Review`,image: '',summary: ``,slug: ""},
			B0185F07GS: {href: "https://amzn.to/3z3Mzom",nameProduct: `Review PORTER-CABLE 20V MAX 8-Tool Cordless Drill Combo Kit`,image: '',summary: ``,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/2SVC5aa",nameProduct: `NordicTrack T Series Treadmill Review`,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3wY7OGn",nameProduct: `Whynter Elite ARC 122DS 12,000 BTU`,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/3ppSno4",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B01AWXC70U: {href: "https://amzn.to/3wXl4Lj",nameProduct: `Intex Pure Spa 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B01B4XUQI2: {href: "https://amzn.to/3uU0t9B",nameProduct: `Frigidaire 8000 BTU Window Air Conditioner `,image: '',summary: ``,slug: ""},
			B01BM659ZG: {href: "https://amzn.to/3z0PDSi",nameProduct: `Aprilaire Dehumidifier`,image: '',summary: ``,slug: ""},
			B01D3FOD0Q: {href: "https://amzn.to/3clx0yF",nameProduct: `LG LW8016ER 8,000 BTU 115V Window Mounted `,image: '',summary: ``,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/34SIPIu",nameProduct: `Winix 5500-2 Air Purifier`,image: '',summary: ``,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/34NvMbx",nameProduct: `Mr. Heater MH18B Big Buddy Indoor Propane Heater`,image: '',summary: ``,slug: ""},
			B01DEWZUG4: {href: "https://amzn.to/3uY1ddE",nameProduct: `Panasonic Microwave Oven NN-SN686S`,image: '',summary: ``,slug: ""},
			B01DTIC778: {href: "https://amzn.to/3plz5jA",nameProduct: `Sun Joe MJ401E-PRO Electric Lawn Mower`,image: '',summary: ``,slug: ""},
			B01DV3849Q: {href: "https://amzn.to/3fQbvbo",nameProduct: `Infinity IT-8500X3 3D Zero Gravity Massage Chair Review`,image: '',summary: ``,slug: ""},
			B01E0NP5HU: {href: "https://amzn.to/3uNYSC0",nameProduct: `Seatcraft Dynasty Home Theater Seating`,image: '',summary: ``,slug: ""},
			B01H4UICZ8: {href: "https://amzn.to/3xcA2xt",nameProduct: `Instep Bike Trailer`,image: '',summary: ``,slug: ""},
			B01H7F0RPI: {href: "https://amzn.to/3uS6WSf",nameProduct: `Schwinn LOOP folding bike`,image: '',summary: ``,slug: ""},
			B01ICHJIM8: {href: "https://amzn.to/3x4EAG5",nameProduct: `BestOffice Gaming Chair`,image: '',summary: ``,slug: ""},
			B01IENFJ14: {href: "https://amzn.to/3vXYAd2",nameProduct: `Dyson V8 Absolute Cordless Stick`,image: '',summary: ``,slug: ""},
			B01IRMBG7I: {href: "https://amzn.to/2T0rcUu",nameProduct: `Panda 3200 rpm Portable Spin Dryer Review`,image: '',summary: ``,slug: ""},
			B01J664WSY: {href: "https://amzn.to/2RpJyhn",nameProduct: `Vornado VMH600 Whole Room Stainless Steel`,image: '',summary: ``,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/34PGspT",nameProduct: `Z Grills Wood Pellet Grill Smoker Review `,image: '',summary: ``,slug: ""},
			B01L9X99GC: {href: "https://amzn.to/3io9Yen",nameProduct: `Best Choice Products 7.5ft Premium Spruce Artificial Holiday Christmas Tree`,image: '',summary: ``,slug: ""},
			B01LW3SOPE: {href: "https://amzn.to/3vW0rz1",nameProduct: `AlorAir Basement/Crawl Space Dehumidifiers`,image: '',summary: ``,slug: ""},
			B01LW76AKC: {href: "https://amzn.to/3plZgXr",nameProduct: `Polk Audio MagniFi Mini Home Theater Surround Sound Bar`,image: '',summary: ``,slug: ""},
			B01M0L0D90: {href: "https://amzn.to/34T6CrX",nameProduct: `XTERRA Fitness TR150 Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B01M24RKQY: {href: "https://amzn.to/3w0vPg8",nameProduct: `Kahuna Massage Chair LM6800`,image: '',summary: ``,slug: ""},
			B01M716CC2: {href: "https://amzn.to/2S4sCNS",nameProduct: `Braun Series 9 Electric Shaver`,image: '',summary: ``,slug: ""},
			B01M73WPQ7: {href: "https://amzn.to/34Nxgm3",nameProduct: `PuraFlame Alice 50 Inches Recessed Electric Fireplace Review`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3uUEaQM",nameProduct: `ZINUS Shalini Upholstered Platform Bed Frame`,image: '',summary: ``,slug: ""},
			B01MAVR8UW: {href: "https://amzn.to/3z6ridZ",nameProduct: `Upgraded Version Pyle Portable Washer `,image: '',summary: ``,slug: ""},
			B01MCUXSFD: {href: "https://amzn.to/2S2IiBb",nameProduct: `SVS Dual PB16-Ultra Subwoofer`,image: '',summary: ``,slug: ""},
			B01MPX171W: {href: "https://amzn.to/3vTH5uF",nameProduct: `Braun Series 7 Electric Shaver Review`,image: '',summary: ``,slug: ""},
			B01MRZ02TL: {href: "https://amzn.to/3fV9WsZ",nameProduct: `Homall Gaming Chair Office Chair`,image: '',summary: ``,slug: ""},
			B01MS22KO3: {href: "https://amzn.to/34NA9Dt",nameProduct: `Human Touch Novo XT Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B01N0KXNFX: {href: "https://amzn.to/3cgb200",nameProduct: `Zinus 6 Inch Spring Twin Mattress Review`,image: '',summary: ``,slug: ""},
			B01N4RO2F4: {href: "https://amzn.to/3pm4imw",nameProduct: `Schwinn Rascal Bike Pet Trailer`,image: '',summary: ``,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/3vX7xmZ",nameProduct: `Rheem RTEX-13 Residential Tankless Water Heater Review`,image: '',summary: ``,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/2T14rzG",nameProduct: `Real Relax 2020 Massage Chair`,image: '',summary: ``,slug: ""},
			B06W54K29J: {href: "https://amzn.to/3g4i88Q",nameProduct: `Levoit LV-PUR131 Air Purifier `,image: '',summary: ``,slug: ""},
			B06XBF75QJ: {href: "https://amzn.to/3fR64cc",nameProduct: `LG LP0817WSR 8,000 BTU`,image: '',summary: ``,slug: ""},
			B06XKRWWSG: {href: "https://amzn.to/3uSxNxD",nameProduct: `Sony STR-DN1080 7.2-ch Surround Sound Home Theater AV Receiver`,image: '',summary: ``,slug: ""},
			B06XPGHMGF: {href: "https://amzn.to/3igJhIr",nameProduct: `Seatcraft Omega Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B06Y49GJX4: {href: "https://amzn.to/2TK3IU7",nameProduct: `Summer Waves 10ft x 30in Quick Set Inflatable Above Ground Pool`,image: '',summary: ``,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/3w0wK04",nameProduct: `Review Best Choice Portable`,image: '',summary: ``,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/3g93vBr",nameProduct: `LEVOIT LV H132 Air Purifier Review`,image: '',summary: ``,slug: ""},
			B071FFSN22: {href: "https://amzn.to/3z6rObV",nameProduct: `Milliard Diplomat Folding`,image: '',summary: ``,slug: ""},
			B071HP9PDR: {href: "https://amzn.to/3uRek03",nameProduct: `ALORAIR Commercial Water Damage Restoration Dehumidifier`,image: '',summary: ``,slug: ""},
			B072VLKC4P: {href: "https://amzn.to/3uNHQ76",nameProduct: `Ashley Furniture Yandel Power Lift Recliner`,image: '',summary: ``,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/34PXHaG",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B073FNDD9F: {href: "https://amzn.to/3ciRKav",nameProduct: `Intex 24ft X 12ft X 52in Ultra Frame Rectangular Pool Review`,image: '',summary: ``,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/3uSylDH",nameProduct: `hOmeLabs 70 Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B073W1R4XQ: {href: "https://amzn.to/3wY9fEH",nameProduct: `Edifier R1850DB Active Bookshelf Speakers`,image: '',summary: ``,slug: ""},
			B073X8ZBRL: {href: "https://amzn.to/34WELH7",nameProduct: `Leggett & Platt Adjustable Bed`,image: '',summary: ``,slug: ""},
			B073ZC16ZD: {href: "https://amzn.to/3uTJHau",nameProduct: `Magic Chef White MCSTCW09W1 0.9 cu. ft. Compact Washer`,image: '',summary: ``,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/2T1UTok",nameProduct: `Review Swiss Madison St. Tropez Toilet`,image: '',summary: ``,slug: ""},
			B074D6VDT1: {href: "https://amzn.to/3fSQY6j",nameProduct: `National Tree 21 Foot Kingswood Fir Pencil Tree`,image: '',summary: ``,slug: ""},
			B074ML6THR: {href: "https://amzn.to/3uSyuHf",nameProduct: `Brondell Swash SE600 Bidet Toilet Seat Review`,image: '',summary: ``,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/3ipr8sh",nameProduct: `Brondell Swash SE400 Seat Review`,image: '',summary: ``,slug: ""},
			B074PYH768: {href: "https://amzn.to/3fQdGvA",nameProduct: `hOmeLabs Compact Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B074R7GK8V: {href: "https://amzn.to/3fTqT6R",nameProduct: `COSTWAY Mini Washing Machine Review`,image: '',summary: ``,slug: ""},
			B074T9FRT7: {href: "https://amzn.to/3vZBqTK",nameProduct: `Vornado VMH300 Whole Room Metal Heater`,image: '',summary: ``,slug: ""},
			B075FBJXZ7: {href: "https://amzn.to/3wQu8BQ",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed Review`,image: '',summary: ``,slug: ""},
			B076KKX4BC: {href: "https://amzn.to/3cmcgH5",nameProduct: `Xiaomi Mi Electric Scooter Review`,image: '',summary: ``,slug: ""},
			B076QLXHDH: {href: "https://amzn.to/3z1XHSN",nameProduct: `Frigidaire FFRA0511U1 Air`,image: '',summary: ``,slug: ""},
			B076RTR86T: {href: "https://amzn.to/3fSRaT5",nameProduct: `Direct Spa Model M 780D Hot Tub 7-Person 73-Jet Lounger Spa Review`,image: '',summary: ``,slug: ""},
			B0779KHLXJ: {href: "https://amzn.to/3vX8vj7",nameProduct: `Marantz AV Receiver SR8012 - First-Ever High Performance 11.2 Channel`,image: '',summary: ``,slug: ""},
			B077N51CR2: {href: "https://amzn.to/3vZBClW",nameProduct: `Homall Single Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B077PBGYVD: {href: "https://amzn.to/3ik6n16",nameProduct: `Seatcraft Anthem Home Theater Seating`,image: '',summary: ``,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/3fVbGCx",nameProduct: `LUNA Adult Weighted Blanket Review`,image: '',summary: ``,slug: ""},
			B078964VVX: {href: "https://amzn.to/3uVUcdn",nameProduct: `Westinghouse WGen7500DF Dual Fuel`,image: '',summary: ``,slug: ""},
			B078C6VHDD: {href: "https://amzn.to/3uSyYx3",nameProduct: `SVS PB-4000 Subwoofer `,image: '',summary: ``,slug: ""},
			B0792PD6TY: {href: "https://amzn.to/2SUkuzn",nameProduct: `Review Woodbridge b-0030/bts160`,image: '',summary: ``,slug: ""},
			B07983G4D4: {href: "https://amzn.to/3fSR9hT",nameProduct: `DynastyMattress DM9000s Split King Adjustable `,image: '',summary: ``,slug: ""},
			B079K4L5BD: {href: "https://amzn.to/3fV4YMw",nameProduct: `ZINUS Ricardo Sofa Couch`,image: '',summary: ``,slug: ""},
			B079YW5VQL: {href: "https://amzn.to/2S3t8M3",nameProduct: `Sony STR-DH790 7.2-ch Surround Sound Home`,image: '',summary: ``,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/3ckqI2m",nameProduct: `Nectar Mattress Review`,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/3z4anIV",nameProduct: `SUPER DEAL Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07B9NP4GF: {href: "https://amzn.to/3uOMstv",nameProduct: `Zinus Memory Foam 9 Inch BioFusion Mattress`,image: '',summary: ``,slug: ""},
			B07BKMSJ6X: {href: "https://amzn.to/3cmGEkO",nameProduct: `REC TEC RT-700`,image: '',summary: ``,slug: ""},
			B07BN3B3YT: {href: "https://amzn.to/2RrPSF6",nameProduct: `Avanti STW20D2P portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07BNVST4P: {href: "https://amzn.to/3vTRqGJ",nameProduct: `SWAGTRON Swagcycle EB5 Series Aluminum Folding Ebike `,image: '',summary: ``,slug: ""},
			B07C44DM6D: {href: "https://amzn.to/3x0rsle",nameProduct: `Dupray Neat Steam Cleaner`,image: '',summary: ``,slug: ""},
			B07C49F2LD: {href: "https://amzn.to/353EBOB",nameProduct: `Denon-AVR-S540BT-Receiver - Review 2021`,image: '',summary: ``,slug: ""},
			B07CHYKRK7: {href: "https://amzn.to/3ppWEYh",nameProduct: `COMFEE' Rice Cooker, Slow Cooker, Steamer, Stewpot, Sauté All in One`,image: '',summary: ``,slug: ""},
			B07CN38M23: {href: "https://amzn.to/3uUGes0",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,image: '',summary: ``,slug: ""},
			B07CYGLK5G: {href: "https://amzn.to/3gbZPif",nameProduct: `Yamaha P-125 Digital Piano Review`,image: '',summary: ``,slug: ""},
			B07CZ1CF79: {href: "https://amzn.to/3ifQ2KJ",nameProduct: `Arctic Dreams 10" Hybrid Cooling Gel Mattress`,image: '',summary: ``,slug: ""},
			B07CZ5K355: {href: "https://amzn.to/3gbZZWT",nameProduct: `Rachio 3 Smart Sprinkler Controller`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/34SLF06",nameProduct: `YOSUDA Indoor Cycling Bike Stationary`,image: '',summary: ``,slug: ""},
			B07DFBQV15: {href: "https://amzn.to/3ckr2hA",nameProduct: `REL Acoustics HT1205 Subwoofer`,image: '',summary: ``,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/3pnxzgM",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner`,image: '',summary: ``,slug: ""},
			B07F39ZRCQ: {href: "https://amzn.to/34P2etV",nameProduct: `Bose Bass Module 700`,image: '',summary: ``,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/2SVFjdM",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Review `,image: '',summary: ``,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/3uVeZhh",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool`,image: '',summary: ``,slug: ""},
			B07F618LKC: {href: "https://amzn.to/3uQLLjr",nameProduct: `COSTWAY Compact Laundry Dryer`,image: '',summary: ``,slug: ""},
			B07FDFP79J: {href: "https://amzn.to/2Sd4qIT",nameProduct: `Ninja Foodi 9-in-1 Pressure Unboxing`,image: '',summary: ``,slug: ""},
			B07FKJHNZX: {href: "https://amzn.to/3iiBsSE",nameProduct: `Bestway 57266-19 Round Kids Inflatable Pool`,image: '',summary: ``,slug: ""},
			B07FP186CN: {href: "https://amzn.to/34NdPcY",nameProduct: `TOTO Neorest NX1 Electronic Dual Flush Toilet`,image: '',summary: ``,slug: ""},
			B07FSYZVTZ: {href: "https://amzn.to/3wYat2L",nameProduct: `SereneLife Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B07FX7Z3NL: {href: "https://amzn.to/3pm6tqr",nameProduct: `Shark Navigator Upright Vacuum`,image: '',summary: ``,slug: ""},
			B07FZ8S74R: {href: "https://amzn.to/3vY1Oxa",nameProduct: `Echo Dot (3rd Gen)`,image: '',summary: ``,slug: ""},
			B07GNDDNMW: {href: "https://amzn.to/3fSS7e1",nameProduct: `SIHOO Ergonomic Office Chair`,image: '',summary: ``,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/3ijzIZf",nameProduct: `Flume Water Monitor Review`,image: '',summary: ``,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3z1YvHj",nameProduct: `Kahuna LM6800 Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07H1B3PY9: {href: "https://amzn.to/34M33no",nameProduct: `Polk Audio Signa S2 Ultra-Slim TV Sound Bar`,image: '',summary: ``,slug: ""},
			B07H2CKPJV: {href: "https://amzn.to/3cjK1Ja",nameProduct: `Callaway Golf Men's Strata Complete Set`,image: '',summary: ``,slug: ""},
			B07H2NP7PR: {href: "https://amzn.to/2RpDqFL",nameProduct: `Intex 15ft x 42in Prism Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B07H781NMC: {href: "https://amzn.to/2Sbuswi",nameProduct: `WOODBRIDGE T-0019 Cotton White toilet Review`,image: '',summary: ``,slug: ""},
			B07H7R6YTB: {href: "https://amzn.to/3ik7duM",nameProduct: `WOODBRIDGE B-0960S B0960S Smart Bidet seat Toilet`,image: '',summary: ``,slug: ""},
			B07HB7QBQ2: {href: "https://amzn.to/3g6vJwy",nameProduct: `NordicTrack T Series Treadmill`,image: '',summary: ``,slug: ""},
			B07HVSR8RF: {href: "https://amzn.to/34RzCQE",nameProduct: `SUPER DEAL Portable Compact Washing Machine`,image: '',summary: ``,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3z3cOvk",nameProduct: `Review Nod by Tuft And Needle Mattress`,image: '',summary: ``,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/3ig66MB",nameProduct: `ZENY Portable Clothes Washing Machine`,image: '',summary: ``,slug: ""},
			B07JGRJHV1: {href: "https://amzn.to/3fT0p5x",nameProduct: `NAKTO 26" City Adult Electric Bicycle`,image: '',summary: ``,slug: ""},
			B07K7YXCFD: {href: "https://amzn.to/3vUkqhv",nameProduct: `Cangshan N1 Series Review`,image: '',summary: ``,slug: ""},
			B07KKFDM1M: {href: "https://amzn.to/3ciTjFp",nameProduct: `Craftsman V60 Cordless Lawn Mower`,image: '',summary: ``,slug: ""},
			B07KQ6S5N1: {href: "https://amzn.to/3ihPsfx",nameProduct: `ONSON Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07L1P4SPB: {href: "https://amzn.to/34PZXyG",nameProduct: `Inofia Responsive Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B07L4ZQMDX: {href: "https://amzn.to/3v01Y6c",nameProduct: `NOUHAUS Ergo3D Ergonomic Office Chair Review`,image: '',summary: ``,slug: ""},
			B07M8F5P7B: {href: "https://amzn.to/3z6fxUQ",nameProduct: `Dyson V7 Allergy HEPA Cord-Free Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07M949RQS: {href: "https://amzn.to/3wWeMvC",nameProduct: `Valencia Tuscany Home Theater Seating`,image: '',summary: ``,slug: ""},
			B07MCDL9N3: {href: "https://amzn.to/3g9qFrb",nameProduct: `hOmeLabs Freestanding Commercial`,image: '',summary: ``,slug: ""},
			B07MKLJLY4: {href: "https://amzn.to/2T13mrA",nameProduct: `Seatcraft Pantheon Big & Tall Home`,image: '',summary: ``,slug: ""},
			B07MRG5F4J: {href: "https://amzn.to/34RzVeg",nameProduct: `Cuisinart TOA-65 Digital Convection Toaster Oven Airfryer`,image: '',summary: ``,slug: ""},
			B07MXQQQZ5: {href: "https://amzn.to/353G1Zr",nameProduct: `Touchstone 80036 - Sideline Elite Electric Fireplace`,image: '',summary: ``,slug: ""},
			B07MY2H45K: {href: "https://amzn.to/3fR8O9u",nameProduct: `LINENSPA 3 Inch Gel Infused Memory Foam Mattress Topper`,image: '',summary: ``,slug: ""},
			B07N3Z9M7H: {href: "https://amzn.to/34RAcxO",nameProduct: `Keystone KSTAD50B Energy Star`,image: '',summary: ``,slug: ""},
			B07NC2QM6V: {href: "https://amzn.to/3vTKbih",nameProduct: `LG LP1419IVSM 14000 BTU Portable`,image: '',summary: ``,slug: ""},
			B07NRBDMJR: {href: "https://amzn.to/3w6Yn7m",nameProduct: `MIDEA MAD50C1ZWS Dehumidifier for up to 4500 Sq Ft`,image: '',summary: ``,slug: ""},
			B07PB37R7H: {href: "https://amzn.to/3z6hXTe",nameProduct: `Hbada Ergonomic Office Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B07PBFKXW9: {href: "https://amzn.to/3clh1k7",nameProduct: `Sony XB72 High Power Home Audio System`,image: '',summary: ``,slug: ""},
			B07PDXKSGJ: {href: "https://amzn.to/3ppl7gk",nameProduct: `MIDEA EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B07PL6LDP1: {href: "https://amzn.to/3fTHbNb",nameProduct: `Sony HT-S350 Soundbar Review`,image: '',summary: ``,slug: ""},
			B07Q19RL7D: {href: "https://amzn.to/3pmmFId",nameProduct: `Subrtex 3 Inch Gel-Infused Memory Foam Bed Mattress`,image: '',summary: ``,slug: ""},
			B07Q9MDWQH: {href: "https://amzn.to/3vU7vwn",nameProduct: `Hoover ONEPWR Blade+ Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07QLR12BV: {href: "https://amzn.to/3cgdDag",nameProduct: `Hbada Office Task Desk Chair Review`,image: '',summary: ``,slug: ""},
			B07QV8PMBY: {href: "https://amzn.to/3fT1aeT",nameProduct: `Massage Chair by OOTORI, Zero Gravity Massage Chair`,image: '',summary: ``,slug: ""},
			B07QX2BYDH: {href: "https://amzn.to/3fR9knW",nameProduct: `Amazon Basics Gaming Computer Desk`,image: '',summary: ``,slug: ""},
			B07QYC1TFB: {href: "https://amzn.to/2T17NCM",nameProduct: `Ohana 7-Piece Outdoor Furniture Review`,image: '',summary: ``,slug: ""},
			B07RCNHTLS: {href: "https://amzn.to/3fRstWN",nameProduct: `Instant Pot Duo Nova 7-in-1 Electric Pressure Cooker`,image: '',summary: ``,slug: ""},
			B07RHQ5YNZ: {href: "https://amzn.to/34P3zkr",nameProduct: `Frigidaire 12,000 BTU 115V Window`,image: '',summary: ``,slug: ""},
			B07RRF95QW: {href: "https://amzn.to/3uOOeLb",nameProduct: `EuroMini Zizzo CAMPO Folding Bike Review`,image: '',summary: ``,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/2TI1YL4",nameProduct: `WoodBridge T 0001 Review2020`,image: '',summary: ``,slug: ""},
			B07S2348R9: {href: "https://amzn.to/2TAaA6e",nameProduct: `SUPER DEAL 2IN1 Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B07S39CW8Q: {href: "https://amzn.to/3vUVQ0d",nameProduct: `Giantex Full Automatic Washing Machine Portable`,image: '',summary: ``,slug: ""},
			B07S76WBGF: {href: "https://amzn.to/3igk4hq",nameProduct: `Ninja Foodi 5-in-1 4-Qt`,image: '',summary: ``,slug: ""},
			B07SFJXLYW: {href: "https://amzn.to/3clVurD",nameProduct: `SereneLife 12,000 BTU Portable 3 in 1 Air Conditioner for Rooms Up to 450 Sq. Ft`,image: '',summary: ``,slug: ""},
			B07SG4KNT4: {href: "https://amzn.to/3fP3ovL",nameProduct: `Deik Cordless Stick Vacuum Review`,image: '',summary: ``,slug: ""},
			B07SQ9YCJB: {href: "https://amzn.to/2TKOJcw",nameProduct: `BLACK+DECKER Powerseries Cordless`,image: '',summary: ``,slug: ""},
			B07SS48CC7: {href: "https://amzn.to/3v02Qru",nameProduct: `Hayward W3HP21404T Pool Heat Pump Review`,image: '',summary: ``,slug: ""},
			B07SV9516S: {href: "https://amzn.to/3wYbuI7",nameProduct: `Hayward Pool Heater Review`,image: '',summary: ``,slug: ""},
			B07TC3659T: {href: "https://amzn.to/3ig6Wcd",nameProduct: `KUPPET Compact Twin Tub Portable Mini Washing`,image: '',summary: ``,slug: ""},
			B07TDHXBYT: {href: "https://amzn.to/2TAhkkA",nameProduct: `Atlantic Furniture Deerfield Murphy Bed Chest`,image: '',summary: ``,slug: ""},
			B07TDP2MMQ: {href: "https://amzn.to/2SYgFsX",nameProduct: `KUPPET Compact Twin Tub Portable`,image: '',summary: ``,slug: ""},
			B07TGQZGGZ: {href: "https://amzn.to/3uVqhBU",nameProduct: `NordicTrack Commercial Studio Cycle Review`,image: '',summary: ``,slug: ""},
			B07V48X7HG: {href: "https://amzn.to/3wYyS8p",nameProduct: `Review LG LW1019IVSM Energy Star`,image: '',summary: ``,slug: ""},
			B07VC44C68: {href: "https://amzn.to/3cCE1LV",nameProduct: `WORX WR150 Landroid L 20V Robotic Lawn Mower`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/3wTDZqk",nameProduct: `Farberware FDW05ASBWHA Complete Portable Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B07VRWZCDS: {href: "https://amzn.to/3ik8p1e",nameProduct: `Sven and Son King Adjustable Bed Base Frame Platinum`,image: '',summary: ``,slug: ""},
			B07VVK39F7: {href: "https://amzn.to/34RSijf",nameProduct: `LEVOIT Air Purifier for Home Allergies Pets Hair Smokers in Bedroom`,image: '',summary: ``,slug: ""},
			B07W7G23ZG: {href: "https://amzn.to/34PLin3",nameProduct: `Ring Stick Up Cam Solar HD security camera`,image: '',summary: ``,slug: ""},
			B07XBPMBTF: {href: "https://amzn.to/3uYoLPr",nameProduct: `SGorri Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07XBYFS9Z: {href: "https://amzn.to/3fRafET",nameProduct: `Zero Gravity Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B07XKCMKWB: {href: "https://amzn.to/2TDW4KJ",nameProduct: `JOOLA Inside - Professional MDF Indoor `,image: '',summary: ``,slug: ""},
			B07Y8BXBX8: {href: "https://amzn.to/3ifREEh",nameProduct: `Gabrylly Ergonomic Mesh Office Chair Review`,image: '',summary: ``,slug: ""},
			B081DG1BRW: {href: "https://amzn.to/3wSIFNg",nameProduct: `Portable Washing Machine KUPPET 16 5lbs`,image: '',summary: ``,slug: ""},
			B081RG8JYR: {href: "https://amzn.to/3vTi5n6",nameProduct: `Waykar 2000 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B082324K53: {href: "https://amzn.to/34PCA8p",nameProduct: `Intex 6 Person Hot Tub Review`,image: '',summary: ``,slug: ""},
			B082LXF4VK: {href: "https://amzn.to/3uTNlkG",nameProduct: `Intex PureSpa Greywood Deluxe 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B083G9WVNC: {href: "https://amzn.to/3fV7KRW",nameProduct: `Panda PAN6320W Portable Machine`,image: '',summary: ``,slug: ""},
			B083LL68Z5: {href: "https://amzn.to/3w0B7Iw",nameProduct: `Intex Simple Spa Outdoor Portable Hot Tub`,image: '',summary: ``,slug: ""},
			B083Q2L4VZ: {href: "https://amzn.to/3uSBWBH",nameProduct: `Homech Inflatable Swimming Pools`,image: '',summary: ``,slug: ""},
			B084DBC9MN: {href: "https://amzn.to/2Rnokk2",nameProduct: `Danby DDR050BJWDB 50 Pint Energy Star Dehumidifier`,image: '',summary: ``,slug: ""},
			B084P72GYX: {href: "https://amzn.to/3v2UZJL",nameProduct: `Fitness Reality Multi Function Adjustable Power Rack Squat Stand`,image: '',summary: ``,slug: ""},
			B085797ZFF: {href: "https://amzn.to/3uVhvnJ",nameProduct: `MIDEA MAW05M1BWT Window air conditioner 5000 BTU`,image: '',summary: ``,slug: ""},
			B0861HFYW1: {href: "https://amzn.to/3uQNSDT",nameProduct: `LUCID 10 Inch 2020 Gel Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B0866Y33PL: {href: "https://amzn.to/3cktcxI",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B0867GMW9X: {href: "https://amzn.to/2TJekCF",nameProduct: `Midea U Inverter Window Air Conditioner 12,000BTU`,image: '',summary: ``,slug: ""},
			B086Q2M7FK: {href: "https://amzn.to/2TLjgXF",nameProduct: `Rancilio Silvia M V6 Espresso Machine`,image: '',summary: ``,slug: ""},
			B087Q3PTJP: {href: "https://amzn.to/2T0wqj4",nameProduct: `Ugears Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B088T949GP: {href: "https://amzn.to/3pnUY1v",nameProduct: `OOTORI RL900 Full Body Electric Massage Chair`,image: '',summary: ``,slug: ""},
			B0894K616X: {href: "https://amzn.to/3gaTNyq",nameProduct: `Dahon Mariner D8 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B0897Q7VH2: {href: "https://amzn.to/3fSUT31",nameProduct: `Dahon Dream D6 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B089JS623C: {href: "https://amzn.to/2SfDtEq",nameProduct: `Linenspa 12 Inch Memory Hybrid Plush Mattress`,image: '',summary: ``,slug: ""},
			B08BPJ76GP: {href: "https://amzn.to/2T0wtvg",nameProduct: `Frigidaire 50 Pint FFAD5033W1 Dehumidifier`,image: '',summary: ``,slug: ""},
			B08FKX9KMD: {href: "https://amzn.to/2S3Gmsd",nameProduct: `Beginner Cycle Bike Workout With Sunny Health & Fitness Cycling Bike`,image: '',summary: ``,slug: ""},
			B08GH4NFDH: {href: "https://amzn.to/2S4wmPq",nameProduct: `GoPlus Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B08GYL2CBM: {href: "https://amzn.to/3vU8Vab",nameProduct: `Zinus 14 Inch Gel Memory Foam Pocket Spring Hybrid Mattress`,image: '',summary: ``,slug: ""},
			B08HN5WLMM: {href: "https://amzn.to/3illUxE",nameProduct: `OasisCraft Pre lit Snowy Aspen Spruce Christmas Tree`,image: '',summary: ``,slug: ""},
			B08HYXW1NL: {href: "https://amzn.to/3uUhD6L",nameProduct: `iRest SL Track Massage Chair Recliner, Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B08LG7GNMJ: {href: "https://amzn.to/3prlgQK",nameProduct: `Ootori N503 Deluxe Massage Chair`,image: '',summary: ``,slug: ""},
			B08LK72YV3: {href: "https://amzn.to/3uOsXBz",nameProduct: `Dahon Launch D8 Review`,image: '',summary: ``,slug: ""},
			B08NSVXHB6: {href: "https://amzn.to/3z6UdhI",nameProduct: `Essential Hot Tubs Polara Review`,image: '',summary: ``,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/3vTyubm",nameProduct: `Essential Hot Tubs 67-Jet Syracuse Hot Tub`,image: '',summary: ``,slug: ""},
			B08WYYNXKQ: {href: "https://amzn.to/3puUjeP",nameProduct: `ECOTRIC Fat Tire Electric Bike Beach Snow Bicycle`,image: '',summary: ``,slug: ""},
			MCSDRY15W: {href: "https://amzn.to/3vY4CKI",nameProduct: `Magic Chef Compact Electric White MCSDRY15W 1.5 cu`,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
