function getData(){
	const keysw = "www.bestreview3s.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B000058TJ3: {href: "https://amzn.to/2Thy8g0",nameProduct: `Intex Swim Center Family Inflatable Pool`,image: '',summary: ``,slug: ""},
			B00005RHPD: {href: "https://amzn.to/3pColNM",nameProduct: `Bosch 1617EVSPK Wood Router Tool Combo Kit`,image: '',summary: ``,slug: ""},
			B000092TT0: {href: "https://amzn.to/355SPOP",nameProduct: `Polk Audio PSW505 12" Powered`,image: '',summary: ``,slug: ""},
			B0000AMK5F: {href: "https://amzn.to/3ziL8Tp",nameProduct: `BOSTITCH Coil Roofing Nailer`,image: '',summary: ``,slug: ""},
			B0002KVQBA: {href: "https://amzn.to/3glit7v",nameProduct: `Polk Audio PSW10 10" Powered Subwoofer`,image: '',summary: ``,slug: ""},
			B000ANEPYO: {href: "https://amzn.to/2RE21qs",nameProduct: `Honeywell HFD-120-Q `,image: '',summary: ``,slug: ""},
			B000BO8AKW: {href: "https://amzn.to/3v9Xx8I",nameProduct: `Butterfly Centrefold 25 Table Tennis Table`,image: '',summary: ``,slug: ""},
			B000GFPTQY: {href: "https://amzn.to/3wgaOxW",nameProduct: `Bose Acoutimass 10 Series IV`,image: '',summary: ``,slug: ""},
			B000UXPFMU: {href: "https://amzn.to/2SfR7HZ",nameProduct: `Pentair SuperFlo Pool Pump`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/3gbK4sE",nameProduct: `DuroMax XP4400E Generator`,image: '',summary: ``,slug: ""},
			B002G51BZU: {href: "https://amzn.to/3vag2tM",nameProduct: `Mr. Heater Portable Buddy Heater`,image: '',summary: ``,slug: ""},
			B002QAYJPO: {href: "https://amzn.to/3pCHTBy",nameProduct: `Honeywell Germ Free Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B002R8CPRY: {href: "https://amzn.to/2ThGrbE",nameProduct: `Sunny Health and Fitness SF E905 Elliptical Machine Cross Trainer `,image: '',summary: ``,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/2RGoqnb",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System`,image: '',summary: ``,slug: ""},
			B003FSTA0U: {href: "https://amzn.to/3zgTACv",nameProduct: `Ultrasport F-Bike and F-Rider Fitness Bike Trainer`,image: '',summary: ``,slug: ""},
			B003MANSNG: {href: "https://amzn.to/359nzOO",nameProduct: `National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B0043E6PLC: {href: "https://amzn.to/3wcBUG3",nameProduct: `BLACK+DECKER Countertop Convection Toaster Oven`,image: '',summary: ``,slug: ""},
			B00467H5YW: {href: "https://amzn.to/3iBYowx",nameProduct: `Sunny Health & Fitness Exercise Cycling Bike`,image: '',summary: ``,slug: ""},
			B004PULVOK: {href: "https://amzn.to/3vaUiOu",nameProduct: `Kohler K-3999-0 Highline Comfort Height `,image: '',summary: ``,slug: ""},
			B004QERFA4: {href: "https://amzn.to/3waLgT1",nameProduct: `Kohler Santa Rosa Comfort Toilet Review`,image: '',summary: ``,slug: ""},
			B0055P70MQ: {href: "https://amzn.to/3pFbZoa",nameProduct: `Technivorm Moccamaster 59616 KBG Coffee Brewer`,image: '',summary: ``,slug: ""},
			B006H1QYBA: {href: "https://amzn.to/3grlGlM",nameProduct: `Steelcase Leap Chair`,image: '',summary: ``,slug: ""},
			B006IY89ZA: {href: "https://amzn.to/3ga1G8l",nameProduct: `Modway Articulate Ergonomic Mesh Office Chair`,image: '',summary: ``,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3cxG17R",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B009IJ2LM4: {href: "https://amzn.to/3g6oBSa",nameProduct: `TOTO Washlet s300e Electronic Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B009IJ2N9U: {href: "https://amzn.to/3ivvMot",nameProduct: `TOTO Washlet s350e Review 2020`,image: '',summary: ``,slug: ""},
			B009SCPYN4: {href: "https://amzn.to/3wcVuSC",nameProduct: `Hudson Bay Spas 4 Person`,image: '',summary: ``,slug: ""},
			B009X43F38: {href: "https://amzn.to/3vgDGoE",nameProduct: `Hobart Handler 140 MIG Welder`,image: '',summary: ``,slug: ""},
			B00AB24XIW: {href: "https://amzn.to/3ziSmXx",nameProduct: `Dri-Eaz LGR 7000XLi Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00AB25016: {href: "https://amzn.to/3g9Py7l",nameProduct: `Dri-Eaz F284 DefendAir HEPA 500 Air Purifier`,image: '',summary: ``,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/3cvKQPk",nameProduct: `Flo by Moen Smart Water Shutoff `,image: '',summary: ``,slug: ""},
			B00CH9QWOU: {href: "https://amzn.to/3cwXHk6",nameProduct: `Breville the Barista Express Espresso Machine`,image: '',summary: ``,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/3vaWRjA",nameProduct: `Touchstone 80001 Onyx Electric `,image: '',summary: ``,slug: ""},
			B00E95K6LU: {href: "https://amzn.to/3cyhe3x",nameProduct: `Schwinn Toddler Balance Bike`,image: '',summary: ``,slug: ""},
			B00EPNDJ24: {href: "https://amzn.to/35dlH7D",nameProduct: `Manitowoc Nugget Ice Machine`,image: '',summary: ``,slug: ""},
			B00EUU5GFK: {href: "https://amzn.to/2TjcRT7",nameProduct: `Serta Ergonomic Executive Office Chair Review`,image: '',summary: ``,slug: ""},
			B00F2CGXGG: {href: "https://amzn.to/3iwjyvK",nameProduct: `Dewalt 10" DWE7491RS Table Saw with Rolling Stand Review`,image: '',summary: ``,slug: ""},
			B00FH441AE: {href: "https://amzn.to/3iAEcuL",nameProduct: `Review 16 Piece Deluxe Edition Christmas Nativity Set`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3wcPDwD",nameProduct: `TOTO MS992CUMFG#01 Neorest`,image: '',summary: ``,slug: ""},
			B00FT5VAWI: {href: "https://amzn.to/3xbbF38",nameProduct: `DeLonghi TRD40615T Full Room Radiant Heater Review`,image: '',summary: ``,slug: ""},
			B00G00BT72: {href: "https://amzn.to/3cyGkiP",nameProduct: `McCulloch MC1375 Canister Steam Cleaner`,image: '',summary: ``,slug: ""},
			B00GBADAT6: {href: "https://amzn.to/3zi4rMj",nameProduct: `JOOLA NOVA Outdoor Table Tennis`,image: '',summary: ``,slug: ""},
			B00GJ1N5VA: {href: "https://amzn.to/2ThL59A",nameProduct: `JOOLA Rally TL - Professional `,image: '',summary: ``,slug: ""},
			B00GN96JFW: {href: "https://amzn.to/3vaWyFh",nameProduct: `Flash Furniture Eclipse Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B00H3DIT14: {href: "https://amzn.to/3valgFU",nameProduct: `DRI EAZ F413 Revolution LGR Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00H3RI32U: {href: "https://amzn.to/3v4rib6",nameProduct: `Touchstone 80004 - Sideline Electric Fireplace`,image: '',summary: ``,slug: ""},
			B00HRT863U: {href: "https://amzn.to/3ix5ORm",nameProduct: `Bestway SaluSpa Miami Inflatable Hot Tub`,image: '',summary: ``,slug: ""},
			B00HXGSBXC: {href: "https://amzn.to/3xaYpLH",nameProduct: `RoyalBaby Kids Bike Boys Girls Freestyle Bicycle`,image: '',summary: ``,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/3gn9zq2",nameProduct: `APEC Drinking Water`,image: '',summary: ``,slug: ""},
			B00IFHPVEU: {href: "https://amzn.to/3ct00V9",nameProduct: `Amazon Basics Leather-Padded Office Chair Review`,image: '',summary: ``,slug: ""},
			B00IWJOOU8: {href: "https://amzn.to/3zjUlur",nameProduct: `Briggs & Stratton P3000 Power Smart Series Inverter Generator`,image: '',summary: ``,slug: ""},
			B00JGRBSS6: {href: "https://amzn.to/3pEI3s9",nameProduct: `Marcy 150-lb Multifunctional Home Gym Station`,image: '',summary: ``,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/3pFLqiP",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum`,image: '',summary: ``,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/3pD3ji9",nameProduct: `Polaris F9550 Robotic Pool`,image: '',summary: ``,slug: ""},
			B00KYB47JU: {href: "https://amzn.to/3itfw7l",nameProduct: `American Spas AM-630LM 5-Person 30-Jet Lounger Spa`,image: '',summary: ``,slug: ""},
			B00LFS0DMG: {href: "https://amzn.to/3v9RtgG",nameProduct: `Steelcase Amia Task Chair Review`,image: '',summary: ``,slug: ""},
			B00MU26OKG: {href: "https://amzn.to/3pJOytN",nameProduct: `Intex Swim Centre Family Lounge Pool`,image: '',summary: ``,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/3gbS2C4",nameProduct: `Hessaire MC37M Portable Evaporative Cooler`,image: '',summary: ``,slug: ""},
			B00NB3P98G: {href: "https://amzn.to/3ixLIXs",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa`,image: '',summary: ``,slug: ""},
			B00OX5B8CW: {href: "https://amzn.to/3xcz8AM",nameProduct: `Intex 12' x 30'' Metal Frame Pool`,image: '',summary: ``,slug: ""},
			B00PKXWIPC: {href: "https://amzn.to/35kqrc1",nameProduct: `Review Safavieh Hudson Shag Collection SGH281A Area Rug`,image: '',summary: ``,slug: ""},
			B00Q7EE928: {href: "https://amzn.to/3v8LMPV",nameProduct: `Xspec 20 inch 7 Speed Folding Compact City Commuter Bike`,image: '',summary: ``,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/2Tcm93s",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B00Q7EPY04: {href: "https://amzn.to/357qJmk",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress Queen`,image: '',summary: ``,slug: ""},
			B00QBZ2BX2: {href: "https://amzn.to/3x8PPgw",nameProduct: `TUFT & NEEDLE Original Mattress`,image: '',summary: ``,slug: ""},
			B00R6AW5S2: {href: "https://amzn.to/3vblsEL",nameProduct: `Makita EB7650TH 75.6 cc MM4 Backpack Blower`,image: '',summary: ``,slug: ""},
			B00R9HVPBK: {href: "https://amzn.to/3gmLsrB",nameProduct: `DHP Emily Futon Sofa Bed`,image: '',summary: ``,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/3pBXVMc",nameProduct: `WEN 56200i Super Quiet 2000 Watt Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B00TVFO08S: {href: "https://amzn.to/3iy3vhc",nameProduct: `Bose Acoustimass 6 Series V Home Theater Speaker System`,image: '',summary: ``,slug: ""},
			B00UVAJU6O: {href: "https://amzn.to/357QkeM",nameProduct: `Classic Brands Cool Ventilated Gel Memory Foam 10 Inch`,image: '',summary: ``,slug: ""},
			B00UWP07LK: {href: "https://amzn.to/2SfxVtT",nameProduct: `Frigidaire 70-Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B00WR1OTY8: {href: "https://amzn.to/3wfkXef",nameProduct: `SVS Ultra Center Channel Loudspeaker`,image: '',summary: ``,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/3czolZM",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine`,image: '',summary: ``,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/3pGwWyQ",nameProduct: `Review La-Z-Boy Delano Big`,image: '',summary: ``,slug: ""},
			B011IH6MBO: {href: "https://amzn.to/3cwlyk0",nameProduct: `Bose Wave SoundTouch Music System IV Review`,image: '',summary: ``,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3g8gtjS",nameProduct: `SmartBidet SB 1000 Smart Electric Bidet Seat`,image: '',summary: ``,slug: ""},
			B012H0K93I: {href: "https://amzn.to/3vb9dIz",nameProduct: `Zinus 12 Inch Cloud Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B013I40R8E: {href: "https://amzn.to/3grEKAi",nameProduct: `Breville BPR700BSS Fast Slow Pro Multi Function Cooker`,image: '',summary: ``,slug: ""},
			B013LIN5W2: {href: "https://amzn.to/3cwNgge",nameProduct: `Polk Audio T50 Home Theater Floor Standing Tower Speaker`,image: '',summary: ``,slug: ""},
			B0165UFOGS: {href: "https://amzn.to/3g8i0Xm",nameProduct: `TOTO SW2014#01 A100 Electronic Bidet Toilet`,image: '',summary: ``,slug: ""},
			B016J0EITS: {href: "https://amzn.to/356ukB5",nameProduct: `SureFire X300 Ultra Series LED WeaponLights`,image: '',summary: ``,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/3wbfbKP",nameProduct: `Steelcase Gesture Chair Review`,image: '',summary: ``,slug: ""},
			B0185F07GS: {href: "https://amzn.to/2SpMyur",nameProduct: `Review PORTER-CABLE 20V MAX 8-Tool Cordless Drill Combo Kit`,image: '',summary: ``,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/3gjc1Oe",nameProduct: `NordicTrack T Series Treadmill Review`,image: '',summary: ``,slug: ""},
			B01B4XUQI2: {href: "https://amzn.to/2ThEgVE",nameProduct: `Frigidaire 8000 BTU Window Air Conditioner `,image: '',summary: ``,slug: ""},
			B01BM659ZG: {href: "https://amzn.to/3pF7OIR",nameProduct: `Aprilaire Dehumidifier`,image: '',summary: ``,slug: ""},
			B01D3FOD0Q: {href: "https://amzn.to/358cU7e",nameProduct: `LG LW8016ER 8,000 BTU 115V Window Mounted `,image: '',summary: ``,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/3cvGBTR",nameProduct: `Winix 5500-2 Air Purifier`,image: '',summary: ``,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/2TjFUpD",nameProduct: `Mr. Heater MH18B Big Buddy Indoor Propane Heater`,image: '',summary: ``,slug: ""},
			B01DV3849Q: {href: "https://amzn.to/3pEDcas",nameProduct: `Infinity IT-8500X3 3D Zero Gravity Massage Chair Review`,image: '',summary: ``,slug: ""},
			B01E0NP5HU: {href: "https://amzn.to/2TQJLLb",nameProduct: `Seatcraft Dynasty Home Theater Seating`,image: '',summary: ``,slug: ""},
			B01H4UICZ8: {href: "https://amzn.to/2RGVueN",nameProduct: `Instep Bike Trailer`,image: '',summary: ``,slug: ""},
			B01H7F0RPI: {href: "https://amzn.to/3gaPTGZ",nameProduct: `Schwinn LOOP folding bike`,image: '',summary: ``,slug: ""},
			B01ICHJIM8: {href: "https://amzn.to/3cxjQyK",nameProduct: `BestOffice Gaming Chair`,image: '',summary: ``,slug: ""},
			B01IENFJ14: {href: "https://amzn.to/3gaQdpb",nameProduct: `Dyson V8 Absolute Cordless Stick`,image: '',summary: ``,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/3wfGOT0",nameProduct: `Z Grills Wood Pellet Grill Smoker Review `,image: '',summary: ``,slug: ""},
			B01L9X99GC: {href: "https://amzn.to/3cyDbzz",nameProduct: `Best Choice Products 7.5ft Premium Spruce Artificial Holiday Christmas Tree`,image: '',summary: ``,slug: ""},
			B01LW3SOPE: {href: "https://amzn.to/3vbK3cw",nameProduct: `AlorAir Basement/Crawl Space Dehumidifiers`,image: '',summary: ``,slug: ""},
			B01LW76AKC: {href: "https://amzn.to/3pFI8fk",nameProduct: `Polk Audio MagniFi Mini Home Theater Surround Sound Bar`,image: '',summary: ``,slug: ""},
			B01M0L0D90: {href: "https://amzn.to/3gcf1NH",nameProduct: `XTERRA Fitness TR150 Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B01M716CC2: {href: "https://amzn.to/3goGzOD",nameProduct: `Braun Series 9 Electric Shaver`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3g6UI4a",nameProduct: `ZINUS Shalini Upholstered Platform Bed Frame`,image: '',summary: ``,slug: ""},
			B01MAVR8UW: {href: "https://amzn.to/3vbd9cj",nameProduct: `Upgraded Version Pyle Portable Washer `,image: '',summary: ``,slug: ""},
			B01MCUXSFD: {href: "https://amzn.to/3cxAWwu",nameProduct: `SVS Dual PB16-Ultra Subwoofer`,image: '',summary: ``,slug: ""},
			B01MPWCS7O: {href: "https://amzn.to/3g7rUZ8",nameProduct: `LUCID LU04QQFSGF2 4 Inch`,image: '',summary: ``,slug: ""},
			B01MPX171W: {href: "https://amzn.to/3xgq9yL",nameProduct: `Braun Series 7 Electric Shaver Review`,image: '',summary: ``,slug: ""},
			B01MRZ02TL: {href: "https://amzn.to/3g9rykQ",nameProduct: `Homall Gaming Chair Office Chair`,image: '',summary: ``,slug: ""},
			B01N0KXNFX: {href: "https://amzn.to/3cwO05n",nameProduct: `Zinus 6 Inch Spring Twin Mattress Review`,image: '',summary: ``,slug: ""},
			B01N4RO2F4: {href: "https://amzn.to/2TY4fSr",nameProduct: `Schwinn Rascal Bike Pet Trailer`,image: '',summary: ``,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/3vaRjFI",nameProduct: `Rheem RTEX-13 Residential Tankless Water Heater Review`,image: '',summary: ``,slug: ""},
			B06W54K29J: {href: "https://amzn.to/3zb2tO1",nameProduct: `Levoit LV-PUR131 Air Purifier `,image: '',summary: ``,slug: ""},
			B06XKRWWSG: {href: "https://amzn.to/3zj3Ha0",nameProduct: `Sony STR-DN1080 7.2-ch Surround Sound Home Theater AV Receiver`,image: '',summary: ``,slug: ""},
			B06Y49GJX4: {href: "https://amzn.to/3pE7eLz",nameProduct: `Summer Waves 10ft x 30in Quick Set Inflatable Above Ground Pool`,image: '',summary: ``,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/3cz9LBv",nameProduct: `LEVOIT LV H132 Air Purifier Review`,image: '',summary: ``,slug: ""},
			B071FFSN22: {href: "https://amzn.to/3gaao6D",nameProduct: `Milliard Diplomat Folding`,image: '',summary: ``,slug: ""},
			B071HP9PDR: {href: "https://amzn.to/3glsz8l",nameProduct: `ALORAIR Commercial Water Damage Restoration Dehumidifier`,image: '',summary: ``,slug: ""},
			B072VLKC4P: {href: "https://amzn.to/3gaeKdQ",nameProduct: `Ashley Furniture Yandel Power Lift Recliner`,image: '',summary: ``,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/3gbIRSi",nameProduct: `hOmeLabs 70 Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B073W1R4XQ: {href: "https://amzn.to/3cuNpkk",nameProduct: `Edifier R1850DB Active Bookshelf Speakers`,image: '',summary: ``,slug: ""},
			B073X8ZBRL: {href: "https://amzn.to/3iwYk12",nameProduct: `Leggett & Platt Adjustable Bed`,image: '',summary: ``,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/3goIMcT",nameProduct: `Review Swiss Madison St. Tropez Toilet`,image: '',summary: ``,slug: ""},
			B074D6VDT1: {href: "https://amzn.to/3cvKkRl",nameProduct: `National Tree 21 Foot Kingswood Fir Pencil Tree`,image: '',summary: ``,slug: ""},
			B075FBJXZ7: {href: "https://amzn.to/2RGVsDz",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed Review`,image: '',summary: ``,slug: ""},
			B0769HHR81: {href: "https://amzn.to/3vcLI1s",nameProduct: `JL Comfurni Gaming Chair`,image: '',summary: ``,slug: ""},
			B076KKX4BC: {href: "https://amzn.to/3xf9Zp1",nameProduct: `Xiaomi Mi Electric Scooter Review`,image: '',summary: ``,slug: ""},
			B0779KHLXJ: {href: "https://amzn.to/2RFFTMn",nameProduct: `Marantz AV Receiver SR8012 - First-Ever High Performance 11.2 Channel`,image: '',summary: ``,slug: ""},
			B077PBGYVD: {href: "https://amzn.to/2TihEnS",nameProduct: `Seatcraft Anthem Home Theater Seating`,image: '',summary: ``,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/2TjfmVO",nameProduct: `LUNA Adult Weighted Blanket Review`,image: '',summary: ``,slug: ""},
			B0792PD6TY: {href: "https://amzn.to/3cx89In",nameProduct: `Review Woodbridge b-0030/bts160`,image: '',summary: ``,slug: ""},
			B079K4L5BD: {href: "https://amzn.to/3562aGf",nameProduct: `ZINUS Ricardo Sofa Couch`,image: '',summary: ``,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/3iwSzjS",nameProduct: `Nectar Mattress Review`,image: '',summary: ``,slug: ""},
			B07B9NP4GF: {href: "https://amzn.to/3pGiOpF",nameProduct: `Zinus Memory Foam 9 Inch BioFusion Mattress`,image: '',summary: ``,slug: ""},
			B07BKMSJ6X: {href: "https://amzn.to/3x7ThIn",nameProduct: `REC TEC RT-700`,image: '',summary: ``,slug: ""},
			B07BNVST4P: {href: "https://amzn.to/2ShpuhK",nameProduct: `SWAGTRON Swagcycle EB5 Series Aluminum Folding Ebike `,image: '',summary: ``,slug: ""},
			B07C44DM6D: {href: "https://amzn.to/2TWVMPt",nameProduct: `Dupray Neat Steam Cleaner`,image: '',summary: ``,slug: ""},
			B07CHYKRK7: {href: "https://amzn.to/3zhgA4k",nameProduct: `COMFEE' Rice Cooker, Slow Cooker, Steamer, Stewpot, Sauté All in One`,image: '',summary: ``,slug: ""},
			B07CN38M23: {href: "https://amzn.to/356Zw33",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,image: '',summary: ``,slug: ""},
			B07CZ1CF79: {href: "https://amzn.to/3zb5D4l",nameProduct: `Arctic Dreams 10" Hybrid Cooling Gel Mattress`,image: '',summary: ``,slug: ""},
			B07CZ5K355: {href: "https://amzn.to/3zeOmXT",nameProduct: `Rachio 3 Smart Sprinkler Controller`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/2TUXmBo",nameProduct: `YOSUDA Indoor Cycling Bike Stationary`,image: '',summary: ``,slug: ""},
			B07DFBQV15: {href: "https://amzn.to/3pEbtqt",nameProduct: `REL Acoustics HT1205 Subwoofer`,image: '',summary: ``,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/3gmTTDh",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner`,image: '',summary: ``,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/3ghhdC4",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Review `,image: '',summary: ``,slug: ""},
			B07FKJHNZX: {href: "https://amzn.to/3pMkJc7",nameProduct: `Bestway 57266-19 Round Kids Inflatable Pool`,image: '',summary: ``,slug: ""},
			B07FP186CN: {href: "https://amzn.to/3waMy0g",nameProduct: `TOTO Neorest NX1 Electronic Dual Flush Toilet`,image: '',summary: ``,slug: ""},
			B07GNDDNMW: {href: "https://amzn.to/3ctr5rh",nameProduct: `SIHOO Ergonomic Office Chair`,image: '',summary: ``,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/2TkPSXR",nameProduct: `Flume Water Monitor Review`,image: '',summary: ``,slug: ""},
			B07H1B3PY9: {href: "https://amzn.to/3zh9Kfi",nameProduct: `Polk Audio Signa S2 Ultra-Slim TV Sound Bar`,image: '',summary: ``,slug: ""},
			B07H2CKPJV: {href: "https://amzn.to/358mebe",nameProduct: `Callaway Golf Men's Strata Complete Set`,image: '',summary: ``,slug: ""},
			B07H781NMC: {href: "https://amzn.to/3gnBDto",nameProduct: `WOODBRIDGE T-0019 Cotton White toilet Review`,image: '',summary: ``,slug: ""},
			B07H7R6YTB: {href: "https://amzn.to/3xb0es3",nameProduct: `WOODBRIDGE B-0960S B0960S Smart Bidet seat Toilet`,image: '',summary: ``,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3xgvCFN",nameProduct: `Review Nod by Tuft And Needle Mattress`,image: '',summary: ``,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/357fcU2",nameProduct: `ZENY Portable Clothes Washing Machine`,image: '',summary: ``,slug: ""},
			B07JGRJHV1: {href: "https://amzn.to/2TkQPiT",nameProduct: `NAKTO 26" City Adult Electric Bicycle`,image: '',summary: ``,slug: ""},
			B07K3G7JBM: {href: "https://amzn.to/3csfbOD",nameProduct: `Schwinn Koen Kids Bike`,image: '',summary: ``,slug: ""},
			B07K3PNJJS: {href: "https://amzn.to/3cuXT3g",nameProduct: `Schwinn Elm Kids Bike`,image: '',summary: ``,slug: ""},
			B07K7YXCFD: {href: "https://amzn.to/2SopVXs",nameProduct: `Cangshan N1 Series Review`,image: '',summary: ``,slug: ""},
			B07KKFDM1M: {href: "https://amzn.to/3xdd8Wq",nameProduct: `Craftsman V60 Cordless Lawn Mower`,image: '',summary: ``,slug: ""},
			B07KQ6S5N1: {href: "https://amzn.to/357C1qQ",nameProduct: `ONSON Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07M949RQS: {href: "https://amzn.to/3gaujCn",nameProduct: `Valencia Tuscany Home Theater Seating`,image: '',summary: ``,slug: ""},
			B07MKLJLY4: {href: "https://amzn.to/3cybfvB",nameProduct: `Seatcraft Pantheon Big & Tall Home`,image: '',summary: ``,slug: ""},
			B07MRG5F4J: {href: "https://amzn.to/3gauAoT",nameProduct: `Cuisinart TOA-65 Digital Convection Toaster Oven Airfryer`,image: '',summary: ``,slug: ""},
			B07MY2H45K: {href: "https://amzn.to/3zkqCS7",nameProduct: `LINENSPA 3 Inch Gel Infused Memory Foam Mattress Topper`,image: '',summary: ``,slug: ""},
			B07N3Z9M7H: {href: "https://amzn.to/3pEO0p2",nameProduct: `Keystone KSTAD50B Energy Star`,image: '',summary: ``,slug: ""},
			B07PDXKSGJ: {href: "https://amzn.to/3zdUkIy",nameProduct: `MIDEA EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B07PL6LDP1: {href: "https://amzn.to/3whTBo0",nameProduct: `Sony HT-S350 Soundbar Review`,image: '',summary: ``,slug: ""},
			B07Q19RL7D: {href: "https://amzn.to/3cuSVU4",nameProduct: `Subrtex 3 Inch Gel-Infused Memory Foam Bed Mattress`,image: '',summary: ``,slug: ""},
			B07QLR12BV: {href: "https://amzn.to/3wdq8eO",nameProduct: `Hbada Office Task Desk Chair Review`,image: '',summary: ``,slug: ""},
			B07QX2BYDH: {href: "https://amzn.to/3vfocky",nameProduct: `Amazon Basics Gaming Computer Desk`,image: '',summary: ``,slug: ""},
			B07RCNHTLS: {href: "https://amzn.to/3gmziig",nameProduct: `Instant Pot Duo Nova 7-in-1 Electric Pressure Cooker`,image: '',summary: ``,slug: ""},
			B07RRF95QW: {href: "https://amzn.to/3xbGapE",nameProduct: `EuroMini Zizzo CAMPO Folding Bike Review`,image: '',summary: ``,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/3gmllRn",nameProduct: `WoodBridge T 0001 Review2020`,image: '',summary: ``,slug: ""},
			B07S2WWNS8: {href: "https://amzn.to/3givdf2",nameProduct: `Gaming Chair Racing by Play HaHa`,image: '',summary: ``,slug: ""},
			B07SG4KNT4: {href: "https://amzn.to/3xhzOVP",nameProduct: `Deik Cordless Stick Vacuum Review`,image: '',summary: ``,slug: ""},
			B07SRYBJ6L: {href: "https://amzn.to/3vaNikw",nameProduct: `Cedric Office Chair`,image: '',summary: ``,slug: ""},
			B07SS48CC7: {href: "https://amzn.to/3zfdDBl",nameProduct: `Hayward W3HP21404T Pool Heat Pump Review`,image: '',summary: ``,slug: ""},
			B07TGQZGGZ: {href: "https://amzn.to/3cydwa7",nameProduct: `NordicTrack Commercial Studio Cycle Review`,image: '',summary: ``,slug: ""},
			B07VC44C68: {href: "https://amzn.to/3itdlkk",nameProduct: `WORX WR150 Landroid L 20V Robotic Lawn Mower`,image: '',summary: ``,slug: ""},
			B07VHKFWQP: {href: "https://amzn.to/3zfJn9m",nameProduct: `SONGMICS Exercise Bike`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/2So1lWE",nameProduct: `Farberware FDW05ASBWHA Complete Portable Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B07VVK39F7: {href: "https://amzn.to/3w6C41P",nameProduct: `LEVOIT Air Purifier for Home Allergies Pets Hair Smokers in Bedroom`,image: '',summary: ``,slug: ""},
			B07XKCMKWB: {href: "https://amzn.to/3guaftU",nameProduct: `JOOLA Inside - Professional MDF Indoor `,image: '',summary: ``,slug: ""},
			B07Z79VCMQ: {href: "https://amzn.to/2RFRL0T",nameProduct: `Fnova Exercise Bike Indoor Cycling`,image: '',summary: ``,slug: ""},
			B0833NW6SN: {href: "https://amzn.to/3vbGaoa",nameProduct: `Russell Hobbs 26051 Cordless Electric Kettle`,image: '',summary: ``,slug: ""},
			B083Q2L4VZ: {href: "https://amzn.to/3iro3I6",nameProduct: `Homech Inflatable Swimming Pools`,image: '',summary: ``,slug: ""},
			B084P72GYX: {href: "https://amzn.to/3gqc8Ys",nameProduct: `Fitness Reality Multi Function Adjustable Power Rack Squat Stand`,image: '',summary: ``,slug: ""},
			B085797ZFF: {href: "https://amzn.to/2ShvHKA",nameProduct: `MIDEA MAW05M1BWT Window air conditioner 5000 BTU`,image: '',summary: ``,slug: ""},
			B0861HFYW1: {href: "https://amzn.to/3x7Zlk7",nameProduct: `LUCID 10 Inch 2020 Gel Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B0882VT6G7: {href: "https://amzn.to/3g7Pvcj",nameProduct: `TaoTronics Air Purifier`,image: '',summary: ``,slug: ""},
			B0894K616X: {href: "https://amzn.to/2SfMde1",nameProduct: `Dahon Mariner D8 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B0897Q7VH2: {href: "https://amzn.to/3584Hjm",nameProduct: `Dahon Dream D6 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B089JS623C: {href: "https://amzn.to/3vc36Du",nameProduct: `Linenspa 12 Inch Memory Hybrid Plush Mattress`,image: '',summary: ``,slug: ""},
			B08B66KGC6: {href: "https://amzn.to/3ctyfvF",nameProduct: `Kesnos 2500 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B08CDWG8LY: {href: "https://amzn.to/3xdqlyI",nameProduct: `Homasy ColorMist Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B08FKX9KMD: {href: "https://amzn.to/3woJyxv",nameProduct: `Beginner Cycle Bike Workout With Sunny Health & Fitness Cycling Bike`,image: '',summary: ``,slug: ""},
			B08HN5WLMM: {href: "https://amzn.to/354IC51",nameProduct: `OasisCraft Pre lit Snowy Aspen Spruce Christmas Tree`,image: '',summary: ``,slug: ""},
			B08Y87T92T: {href: "https://amzn.to/3zbdH57",nameProduct: `Yaheetech Black Office Chair `,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
