function getData(){
	var dataAMZ = {
	B07T5GGR8L: {US: "https://amzn.to/2YJdg0H",CA: "",UK: ""},
	B07F36DGBN: {US: "https://amzn.to/3avjg2Q",CA: "",UK: ""},
	B076QJNK8G: {US: "https://amzn.to/3aB8eJ5",CA: "",UK: ""},
	B009IJ2LM4: {US: "https://amzn.to/36HaT2K",CA: "",UK: ""},
	B07R37RZFK: {US: "https://amzn.to/2MyaXew",CA: "",UK: ""},
	B078GTKSXK: {US: "https://amzn.to/3cH1LiI",CA: "",UK: ""},
	B078HHDV6Q: {US: "https://amzn.to/3jiqgnJ",CA: "",UK: ""},
	B08NT4YBQ3: {US: "https://amzn.to/39KTWGS",CA: "",UK: ""},
	B00BUV305A: {US: "https://amzn.to/3rjDIKI",CA: "",UK: ""},
	B07SS48CC7: {US: "https://amzn.to/39L7qSY",CA: "",UK: ""},
	B00PXLX2TC: {US: "https://amzn.to/39RZhMJ",CA: "",UK: ""},
	B074T9FRT7: {US: "https://amzn.to/2NXtWiS",CA: "",UK: ""},
	B073FKF9B5: {US: "https://amzn.to/3pONMeo",CA: "",UK: ""},
	B07F39F6Z5: {US: "https://amzn.to/39JErPj",CA: "",UK: ""},
	B07F3DP48S: {US: "https://amzn.to/3avQ3op",CA: "",UK: ""},
	B07H2NP7PR: {US: "https://amzn.to/3pShCyz",CA: "",UK: ""},
	B073FNDD9F: {US: "https://amzn.to/3avQeQB",CA: "",UK: ""},
	B00NB3P98G: {US: "https://amzn.to/39NuEYH",CA: "",UK: ""},
	B00LFS0DMG: {US: "https://amzn.to/3oONVgC",CA: "",UK: ""},
	B07N4MXR77: {US: "https://amzn.to/3pQqS6e",CA: "",UK: ""},
	B075FGY7G2: {US: "https://amzn.to/3d6kt3s",CA: "",UK: ""},
	B01D8DAYII: {US: "https://amzn.to/3tWWYQl",CA: "",UK: ""},
	B07TDP2MMQ: {US: "https://amzn.to/3jOMY6R",CA: "",UK: ""},
	B07NRBDMJR: {US: "https://amzn.to/37fQlPc",CA: "",UK: ""},
	B081RG8JYR: {US: "https://amzn.to/3tRe6XL",CA: "",UK: ""},
	B00FT5VAWI: {US: "https://amzn.to/3s8Td8w",CA: "",UK: ""},
	B0131L4E8I: {US: "https://amzn.to/3sfjHFK",CA: "",UK: ""},
	B0897Q7VH2: {US: "https://amzn.to/3uu0vpE",CA: "",UK: ""},
	B07RRF95QW: {US: "https://amzn.to/3dEz1Yt",CA: "",UK: ""},
	B01M73WPQ7: {US: "https://amzn.to/3bpSUQa",CA: "",UK: ""},
	B01CRYWVG2: {US: "https://amzn.to/2ZC6f2k",CA: "",UK: ""},
	B016HUP4M0: {US: "https://amzn.to/2NQjGsY",CA: "",UK: ""},
	B01DV3849Q: {US: "https://amzn.to/3srlGH9",CA: "",UK: ""},
	B01NAUZJPE: {US: "https://amzn.to/2NLd4vI",CA: "",UK: ""},
	B08SXQ7HNQ: {US: "https://amzn.to/2NMjxGV",CA: "",UK: ""},
	B01EHQ5GNS: {US: "https://amzn.to/37M2GLq",CA: "",UK: ""},
	B006IY89ZA: {US: "https://amzn.to/3aQmtLw",CA: "",UK: ""},
	B07QLR12BV: {US: "https://amzn.to/3utWP7b",CA: "",UK: ""},
	B00EUU5GFK: {US: "https://amzn.to/3bwawtu",CA: "",UK: ""},
	B00IFHPVEU: {US: "https://amzn.to/3uziECy",CA: "",UK: ""},
	B07JQL9FPD: {US: "https://amzn.to/3bCxcs7",CA: "",UK: ""},
	B01M0L0D90: {US: "https://amzn.to/2ZM5hk4",CA: "",UK: ""},
	B07FSYZVTZ: {US: "https://amzn.to/3sqQtUq",CA: "",UK: ""},
	B08GH4NFDH: {US: "https://amzn.to/37OvF1f",CA: "",UK: ""},
	B0193V3DJ6: {US: "https://amzn.to/3pT819S",CA: "",UK: ""},
	B07FPRYTSK: {US: "https://amzn.to/2Pcrfe7",CA: "",UK: ""},
	B07TGQZGGZ: {US: "https://amzn.to/3dRr02t",CA: "",UK: ""},
	B08LK72YV3: {US: "https://amzn.to/3kkALr4",CA: "",UK: ""}
	}
	return dataAMZ;
}
