function getData(){
	const keysw = "www.smartbuyzz.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B000058TJ3: {href: "https://amzn.to/3DgtUaQ",nameProduct: `Intex Swim Center Family Inflatable Pool`,image: '',summary: ``,slug: ""},
			B00005RHPD: {href: "https://amzn.to/3cdy9bc",nameProduct: `Bosch 1617EVSPK Wood Router Tool Combo Kit`,image: '',summary: ``,slug: ""},
			B000092TT0: {href: "https://amzn.to/3qzTeoE",nameProduct: `Polk Audio PSW505 12" Powered`,image: '',summary: ``,slug: ""},
			B0000AMK5F: {href: "https://amzn.to/3CgCFjC",nameProduct: `BOSTITCH Coil Roofing Nailer`,image: '',summary: ``,slug: ""},
			B009IX5CZS: {href: "https://amzn.to/3qEiSIH",nameProduct: `Polk Audio PSW10 10" Powered Subwoofer`,image: '',summary: ``,slug: ""},
			B01N0LQJN6: {href: "https://amzn.to/3qzpng5",nameProduct: `Honeywell HFD-120-Q `,image: '',summary: ``,slug: ""},
			B000BO8AKW: {href: "https://amzn.to/30jFVxw",nameProduct: `Butterfly Centrefold 25 Table Tennis Table`,image: '',summary: ``,slug: ""},
			B000GFPTQY: {href: "https://amzn.to/30lgbAQ",nameProduct: `Bose Acoutimass 10 Series IV`,image: '',summary: ``,slug: ""},
			B000UXPFMU: {href: "https://amzn.to/3kF0H21",nameProduct: `Pentair SuperFlo Pool Pump`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/3Fg1I8C",nameProduct: `DuroMax XP4400E Generator`,image: '',summary: ``,slug: ""},
			B002635ODW: {href: "https://amzn.to/3FhV0is",nameProduct: `EcoSmart ECO 27 Electric Tankless Water Heater`,image: '',summary: ``,slug: ""},
			B002G51BZU: {href: "https://amzn.to/3ot5gxx",nameProduct: `Mr. Heater Portable Buddy Heater`,image: '',summary: ``,slug: ""},
			B002QAYJPO: {href: "https://amzn.to/3wMPyRl",nameProduct: `Honeywell Germ Free Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B002R8CPRY: {href: "https://amzn.to/3ndCJfW",nameProduct: `Sunny Health and Fitness SF E905 Elliptical Machine Cross Trainer `,image: '',summary: ``,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3FwXCcr",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System`,image: '',summary: ``,slug: ""},
			B003MANSNG: {href: "https://amzn.to/3Ci4vfF",nameProduct: `National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B0043E6PLC: {href: "https://amzn.to/3Dicn1U",nameProduct: `BLACK+DECKER Countertop Convection Toaster Oven`,image: '',summary: ``,slug: ""},
			B00467H5YW: {href: "https://amzn.to/3osLIsT",nameProduct: `Sunny Health & Fitness Exercise Cycling Bike`,image: '',summary: ``,slug: ""},
			B004PULVOK: {href: "https://amzn.to/3DhlFLH",nameProduct: `Kohler K-3999-0 Highline Comfort Height `,image: '',summary: ``,slug: ""},
			B004QERFA4: {href: "https://amzn.to/3kBQ2Fi",nameProduct: `Kohler Santa Rosa Comfort Toilet Review`,image: '',summary: ``,slug: ""},
			B0052OX876: {href: "https://amzn.to/3DjDxW3",nameProduct: `Lotos LTP5000D 50Amp Non-Touch Pilot Arc Plasma Cutter`,image: '',summary: ``,slug: ""},
			B0055P70MQ: {href: "https://amzn.to/30ztEFw",nameProduct: `Technivorm Moccamaster 59616 KBG Coffee Brewer`,image: '',summary: ``,slug: ""},
			B005BPWN0O: {href: "https://amzn.to/3FeXj5J",nameProduct: `Husqvarna 125B Handheld Blower`,image: '',summary: ``,slug: ""},
			B006H1QYBA: {href: "https://amzn.to/3kAbUk8",nameProduct: `Steelcase Leap Chair`,image: '',summary: ``,slug: ""},
			B006IY89ZA: {href: "https://amzn.to/3HmnJnQ",nameProduct: `Modway Articulate Ergonomic Mesh Office Chair`,image: '',summary: ``,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3HnfQOZ",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B008DBRFBK: {href: "https://amzn.to/3HqoZGw",nameProduct: `Bissell 3624 Spot Clean Professional`,image: '',summary: ``,slug: ""},
			B009IJ2LM4: {href: "https://amzn.to/3kCrmwj",nameProduct: `TOTO Washlet s300e Electronic Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B009IJ2N9U: {href: "https://amzn.to/3CkzJT8",nameProduct: `TOTO Washlet s350e Review 2020`,image: '',summary: ``,slug: ""},
			B009SCPYN4: {href: "https://amzn.to/3kFevcH",nameProduct: `Hudson Bay Spas 4 Person`,image: '',summary: ``,slug: ""},
			B009X43F38: {href: "https://amzn.to/3ovPYrz",nameProduct: `Hobart Handler 140 MIG Welder`,image: '',summary: ``,slug: ""},
			B00A8UPX0Y: {href: "https://amzn.to/3DiWLeC",nameProduct: `National Tree Company Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00AB24XIW: {href: "https://amzn.to/3FdEBvi",nameProduct: `Dri-Eaz LGR 7000XLi Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00AB25016: {href: "https://amzn.to/3nh2tIh",nameProduct: `Dri-Eaz F284 DefendAir HEPA 500 Air Purifier`,image: '',summary: ``,slug: ""},
			B00BUV305A: {href: "https://amzn.to/30vBr7h",nameProduct: `Luraco i7 PLUS Medical Massage`,image: '',summary: ``,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/3qDPkuQ",nameProduct: `Flo by Moen Smart Water Shutoff `,image: '',summary: ``,slug: ""},
			B00CH9QWOU: {href: "https://amzn.to/3qE83GQ",nameProduct: `Breville the Barista Express Espresso Machine`,image: '',summary: ``,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/30n5RJ7",nameProduct: `Touchstone 80001 Onyx Electric `,image: '',summary: ``,slug: ""},
			B00EPNDJ24: {href: "https://amzn.to/3kBRKqc",nameProduct: `Manitowoc Nugget Ice Machine`,image: '',summary: ``,slug: ""},
			B00EUU5GFK: {href: "https://amzn.to/3FdFeFa",nameProduct: `Serta Ergonomic Executive Office Chair Review`,image: '',summary: ``,slug: ""},
			B00F2CGXGG: {href: "https://amzn.to/3oMce0P",nameProduct: `Dewalt 10" DWE7491RS Table Saw with Rolling Stand Review`,image: '',summary: ``,slug: ""},
			B00FADLVAK: {href: "https://amzn.to/30yyq6d",nameProduct: `Review National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00FH441AE: {href: "https://amzn.to/3qCa9H7",nameProduct: `Review 16 Piece Deluxe Edition Christmas Nativity Set`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3HmBdAg",nameProduct: `TOTO MS992CUMFG#01 Neorest`,image: '',summary: ``,slug: ""},
			B00FT5VAWI: {href: "https://amzn.to/3HmpZeO",nameProduct: `DeLonghi TRD40615T Full Room Radiant Heater Review`,image: '',summary: ``,slug: ""},
			B00G00BT72: {href: "https://amzn.to/3orkOSl",nameProduct: `McCulloch MC1375 Canister Steam Cleaner`,image: '',summary: ``,slug: ""},
			B00GBADAT6: {href: "https://amzn.to/3kBSqfh",nameProduct: `JOOLA NOVA Outdoor Table Tennis`,image: '',summary: ``,slug: ""},
			B00GJ1N5VA: {href: "https://amzn.to/3c9hF3U",nameProduct: `JOOLA Rally TL - Professional `,image: '',summary: ``,slug: ""},
			B00GN96JFW: {href: "https://amzn.to/3kFgIov",nameProduct: `Flash Furniture Eclipse Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B00H3RI32U: {href: "https://amzn.to/3kyaruM",nameProduct: `Touchstone 80004 - Sideline Electric Fireplace`,image: '',summary: ``,slug: ""},
			B00HRT863U: {href: "https://amzn.to/3ngp47Z",nameProduct: `Bestway SaluSpa Miami Inflatable Hot Tub`,image: '',summary: ``,slug: ""},
			B00HXGSBXC: {href: "https://amzn.to/30svM1O",nameProduct: `RoyalBaby Kids Bike Boys Girls Freestyle Bicycle`,image: '',summary: ``,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/3HfUanY",nameProduct: `APEC Drinking Water`,image: '',summary: ``,slug: ""},
			B00IFHPVEU: {href: "https://amzn.to/3HnvhqA",nameProduct: `Amazon Basics Leather-Padded Office Chair Review`,image: '',summary: ``,slug: ""},
			B00IWJOOU8: {href: "https://amzn.to/3Fi71o0",nameProduct: `Briggs & Stratton P3000 Power Smart Series Inverter Generator`,image: '',summary: ``,slug: ""},
			B00JGRBSS6: {href: "https://amzn.to/3qzPpQp",nameProduct: `Marcy 150-lb Multifunctional Home Gym Station`,image: '',summary: ``,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/3orpS9j",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum`,image: '',summary: ``,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/3CgOO8m",nameProduct: `Polaris F9550 Robotic Pool`,image: '',summary: ``,slug: ""},
			B00KYB47JU: {href: "https://amzn.to/3orqc81",nameProduct: `American Spas AM-630LM 5-Person 30-Jet Lounger Spa`,image: '',summary: ``,slug: ""},
			B00LFS0DMG: {href: "https://amzn.to/3wOBpTH",nameProduct: `Steelcase Amia Task Chair Review`,image: '',summary: ``,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/3wUzdKI",nameProduct: `Hessaire MC37M Portable Evaporative Cooler`,image: '',summary: ``,slug: ""},
			B01HBKW66M: {href: "https://amzn.to/3nirdzG",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa`,image: '',summary: ``,slug: ""},
			B00OX5B8CW: {href: "https://amzn.to/3ClrwOC",nameProduct: `Intex 12' x 30'' Metal Frame Pool`,image: '',summary: ``,slug: ""},
			B00PKXWIPC: {href: "https://amzn.to/3kCH0HW",nameProduct: `Review Safavieh Hudson Shag Collection SGH281A Area Rug`,image: '',summary: ``,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3HpxaTN",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B00Q7EPY04: {href: "https://amzn.to/3Ccm1Sd",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress Queen`,image: '',summary: ``,slug: ""},
			B00QBZ2BX2: {href: "https://amzn.to/30zCDXg",nameProduct: `TUFT & NEEDLE Original Mattress`,image: '',summary: ``,slug: ""},
			B00R6AW5S2: {href: "https://amzn.to/3HqoWdR",nameProduct: `Makita EB7650TH 75.6 cc MM4 Backpack Blower`,image: '',summary: ``,slug: ""},
			B00R73DYJW: {href: "https://amzn.to/3orri3K",nameProduct: `PuraFlame Western Electric Fireplace Insert`,image: '',summary: ``,slug: ""},
			B00R9HVPBK: {href: "https://amzn.to/30zCZNA",nameProduct: `DHP Emily Futon Sofa Bed`,image: '',summary: ``,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/3wMk1it",nameProduct: `WEN 56200i Super Quiet 2000 Watt Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B00TVFO08S: {href: "https://amzn.to/3Hn1LRP",nameProduct: `Bose Acoustimass 6 Series V Home Theater Speaker System`,image: '',summary: ``,slug: ""},
			B00TVFO0B0: {href: "https://amzn.to/3orrz6M",nameProduct: `Bose Acoustimass 10 series V`,image: '',summary: ``,slug: ""},
			B00UVAJU6O: {href: "https://amzn.to/3qzQPdH",nameProduct: `Classic Brands Cool Ventilated Gel Memory Foam 10 Inch`,image: '',summary: ``,slug: ""},
			B00UWP07LK: {href: "https://amzn.to/3kXzJ5Z",nameProduct: `Frigidaire 70-Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B00W4DCHUC: {href: "https://amzn.to/3Hh8Gfn",nameProduct: `Zinus Ibidun Upholstered Button Tufted Platform Bed`,image: '',summary: ``,slug: ""},
			B00WR1OTY8: {href: "https://amzn.to/3HqpyAb",nameProduct: `SVS Ultra Center Channel Loudspeaker`,image: '',summary: ``,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/30v2aRx",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine`,image: '',summary: ``,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/3kCMMt0",nameProduct: `Review La-Z-Boy Delano Big`,image: '',summary: ``,slug: ""},
			B011IH6MBO: {href: "https://amzn.to/3kCxxRb",nameProduct: `Bose Wave SoundTouch Music System IV Review`,image: '',summary: ``,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3ot27xI",nameProduct: `SmartBidet SB 1000 Smart Electric Bidet Seat`,image: '',summary: ``,slug: ""},
			B012H0K93I: {href: "https://amzn.to/3HqV9SC",nameProduct: `Zinus 12 Inch Cloud Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B013I40R8E: {href: "https://amzn.to/3wKeh8U",nameProduct: `Breville BPR700BSS Fast Slow Pro Multi Function Cooker`,image: '',summary: ``,slug: ""},
			B013LIN5W2: {href: "https://amzn.to/3kCnfQU",nameProduct: `Polk Audio T50 Home Theater Floor Standing Tower Speaker`,image: '',summary: ``,slug: ""},
			B0165UFOGS: {href: "https://amzn.to/3qLx7LQ",nameProduct: `TOTO SW2014#01 A100 Electronic Bidet Toilet`,image: '',summary: ``,slug: ""},
			B016J0EITS: {href: "https://amzn.to/31W7Mo9",nameProduct: `SureFire X300 Ultra Series LED WeaponLights`,image: '',summary: ``,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/30trN52",nameProduct: `Steelcase Gesture Chair Review`,image: '',summary: ``,slug: ""},
			B0185F07GS: {href: "https://amzn.to/3qE9jKa",nameProduct: `Review PORTER-CABLE 20V MAX 8-Tool Cordless Drill Combo Kit`,image: '',summary: ``,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/3cctLJp",nameProduct: `NordicTrack T Series Treadmill Review`,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3kFnDxZ",nameProduct: `Whynter Elite ARC 122DS 12,000 BTU`,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/3qLxDtg",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B01AWXC70U: {href: "https://amzn.to/323RxFN",nameProduct: `Intex Pure Spa 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B01B4XUQI2: {href: "https://amzn.to/2YL6JpW",nameProduct: `Frigidaire 8000 BTU Window Air Conditioner `,image: '',summary: ``,slug: ""},
			B01BM659ZG: {href: "https://amzn.to/3F8fz0C",nameProduct: `Aprilaire Dehumidifier`,image: '',summary: ``,slug: ""},
			B01D3FOD0Q: {href: "https://amzn.to/3HqqZi3",nameProduct: `LG LW8016ER 8,000 BTU 115V Window Mounted `,image: '',summary: ``,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/30tRN0k",nameProduct: `Winix 5500-2 Air Purifier`,image: '',summary: ``,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/3Fh6qCZ",nameProduct: `Mr. Heater MH18B Big Buddy Indoor Propane Heater`,image: '',summary: ``,slug: ""},
			B01DEWZUG4: {href: "https://amzn.to/3kzHHC4",nameProduct: `Panasonic Microwave Oven NN-SN686S`,image: '',summary: ``,slug: ""},
			B01DTIC778: {href: "https://amzn.to/3owfYTW",nameProduct: `Sun Joe MJ401E-PRO Electric Lawn Mower`,image: '',summary: ``,slug: ""},
			B01DV3849Q: {href: "https://amzn.to/3c9DnEZ",nameProduct: `Infinity IT-8500X3 3D Zero Gravity Massage Chair Review`,image: '',summary: ``,slug: ""},
			B01E0NP5HU: {href: "https://amzn.to/3ot31Ky",nameProduct: `Seatcraft Dynasty Home Theater Seating`,image: '',summary: ``,slug: ""},
			B01H4UICZ8: {href: "https://amzn.to/3kBQNhz",nameProduct: `Instep Bike Trailer`,image: '',summary: ``,slug: ""},
			B01H7F0RPI: {href: "https://amzn.to/2YNu4aH",nameProduct: `Schwinn LOOP folding bike`,image: '',summary: ``,slug: ""},
			B01ICHJIM8: {href: "https://amzn.to/3wL5tQa",nameProduct: `BestOffice Gaming Chair`,image: '',summary: ``,slug: ""},
			B01IENFJ14: {href: "https://amzn.to/3qDOrm7",nameProduct: `Dyson V8 Absolute Cordless Stick`,image: '',summary: ``,slug: ""},
			B01IRMBG7I: {href: "https://amzn.to/3ot4TTE",nameProduct: `Panda 3200 rpm Portable Spin Dryer Review`,image: '',summary: ``,slug: ""},
			B01J664WSY: {href: "https://amzn.to/31RRtsu",nameProduct: `Vornado VMH600 Whole Room Stainless Steel`,image: '',summary: ``,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/3kxHNdl",nameProduct: `Z Grills Wood Pellet Grill Smoker Review `,image: '',summary: ``,slug: ""},
			B01L9X99GC: {href: "https://amzn.to/3oxyxa2",nameProduct: `Best Choice Products 7.5ft Premium Spruce Artificial Holiday Christmas Tree`,image: '',summary: ``,slug: ""},
			B01LW3SOPE: {href: "https://amzn.to/3ccZ5I5",nameProduct: `AlorAir Basement/Crawl Space Dehumidifiers`,image: '',summary: ``,slug: ""},
			B01LW76AKC: {href: "https://amzn.to/3qFCv3g",nameProduct: `Polk Audio MagniFi Mini Home Theater Surround Sound Bar`,image: '',summary: ``,slug: ""},
			B01M0L0D90: {href: "https://amzn.to/3FdQz8c",nameProduct: `XTERRA Fitness TR150 Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B01M24RKQY: {href: "https://amzn.to/3ndRT4Q",nameProduct: `Kahuna Massage Chair LM6800`,image: '',summary: ``,slug: ""},
			B01M716CC2: {href: "https://amzn.to/31QGeR5",nameProduct: `Braun Series 9 Electric Shaver`,image: '',summary: ``,slug: ""},
			B01M73WPQ7: {href: "https://amzn.to/3wQwl1d",nameProduct: `PuraFlame Alice 50 Inches Recessed Electric Fireplace Review`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3kEViYF",nameProduct: `ZINUS Shalini Upholstered Platform Bed Frame`,image: '',summary: ``,slug: ""},
			B01MAVR8UW: {href: "https://amzn.to/3wN5LGb",nameProduct: `Upgraded Version Pyle Portable Washer `,image: '',summary: ``,slug: ""},
			B01MCUXSFD: {href: "https://amzn.to/30llLDh",nameProduct: `SVS Dual PB16-Ultra Subwoofer`,image: '',summary: ``,slug: ""},
			B00NB2NOJI: {href: "https://amzn.to/3qDdhTh",nameProduct: `LUCID LU04QQFSGF2 4 Inch`,image: '',summary: ``,slug: ""},
			B01MPX171W: {href: "https://amzn.to/3qDQhDx",nameProduct: `Braun Series 7 Electric Shaver Review`,image: '',summary: ``,slug: ""},
			B01MRZ02TL: {href: "https://amzn.to/3DhMsrh",nameProduct: `Homall Gaming Chair Office Chair`,image: '',summary: ``,slug: ""},
			B01MS22KO3: {href: "https://amzn.to/3qzGoqt",nameProduct: `Human Touch Novo XT Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B01N0KXNFX: {href: "https://amzn.to/3kFgrlD",nameProduct: `Zinus 6 Inch Spring Twin Mattress Review`,image: '',summary: ``,slug: ""},
			B01N4RO2F4: {href: "https://amzn.to/3wNYN3P",nameProduct: `Schwinn Rascal Bike Pet Trailer`,image: '',summary: ``,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/3wMZkTI",nameProduct: `Rheem RTEX-13 Residential Tankless Water Heater Review`,image: '',summary: ``,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/3Ff2rqu",nameProduct: `Real Relax 2020 Massage Chair`,image: '',summary: ``,slug: ""},
			B06W54K29J: {href: "https://amzn.to/3otkRgz",nameProduct: `Levoit LV-PUR131 Air Purifier `,image: '',summary: ``,slug: ""},
			B095KZJ2N8: {href: "https://amzn.to/3Dj3kOg",nameProduct: `LG LP0817WSR 8,000 BTU`,image: '',summary: ``,slug: ""},
			B06XKRWWSG: {href: "https://amzn.to/3wNZDO1",nameProduct: `Sony STR-DN1080 7.2-ch Surround Sound Home Theater AV Receiver`,image: '',summary: ``,slug: ""},
			B06XPGHMGF: {href: "https://amzn.to/2YNxE4D",nameProduct: `Seatcraft Omega Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B06Y49GJX4: {href: "https://amzn.to/3CfbzJN",nameProduct: `Summer Waves 10ft x 30in Quick Set Inflatable Above Ground Pool`,image: '',summary: ``,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/3kC4MUH",nameProduct: `Review Best Choice Portable`,image: '',summary: ``,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/3Ffeu7d",nameProduct: `LEVOIT LV H132 Air Purifier Review`,image: '',summary: ``,slug: ""},
			B071FFSN22: {href: "https://amzn.to/30mL3RE",nameProduct: `Milliard Diplomat Folding`,image: '',summary: ``,slug: ""},
			B071HP9PDR: {href: "https://amzn.to/3ot6V6a",nameProduct: `ALORAIR Commercial Water Damage Restoration Dehumidifier`,image: '',summary: ``,slug: ""},
			B072VLKC4P: {href: "https://amzn.to/3Djdoa2",nameProduct: `Ashley Furniture Yandel Power Lift Recliner`,image: '',summary: ``,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/3FdRMMI",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B073FPL13F: {href: "https://amzn.to/3nog3K9",nameProduct: `Intex 24ft X 12ft X 52in Ultra Frame Rectangular Pool Review`,image: '',summary: ``,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/3celPHK",nameProduct: `hOmeLabs 70 Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B073W1R4XQ: {href: "https://amzn.to/3x0f9GV",nameProduct: `Edifier R1850DB Active Bookshelf Speakers`,image: '',summary: ``,slug: ""},
			B073X8ZBRL: {href: "https://amzn.to/3CbaSRK",nameProduct: `Leggett & Platt Adjustable Bed`,image: '',summary: ``,slug: ""},
			B073ZC16ZD: {href: "https://amzn.to/323Xcf1",nameProduct: `Magic Chef White MCSTCW09W1 0.9 cu. ft. Compact Washer`,image: '',summary: ``,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/3kxM40n",nameProduct: `Review Swiss Madison St. Tropez Toilet`,image: '',summary: ``,slug: ""},
			B074D6VDT1: {href: "https://amzn.to/3Fgs3TR",nameProduct: `National Tree 21 Foot Kingswood Fir Pencil Tree`,image: '',summary: ``,slug: ""},
			B074ML6THR: {href: "https://amzn.to/3HmOA3q",nameProduct: `Brondell Swash SE600 Bidet Toilet Seat Review`,image: '',summary: ``,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/3Flwih7",nameProduct: `Brondell Swash SE400 Seat Review`,image: '',summary: ``,slug: ""},
			B074PYH768: {href: "https://amzn.to/30oqxAv",nameProduct: `hOmeLabs Compact Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B074R7GK8V: {href: "https://amzn.to/3HmOIQs",nameProduct: `COSTWAY Mini Washing Machine Review`,image: '',summary: ``,slug: ""},
			B074T9FRT7: {href: "https://amzn.to/3HyQAWr",nameProduct: `Vornado VMH300 Whole Room Metal Heater`,image: '',summary: ``,slug: ""},
			B075FBJXZ7: {href: "https://amzn.to/3Ho4bPV",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed Review`,image: '',summary: ``,slug: ""},
			B076QLXHDH: {href: "https://amzn.to/3CgMezd",nameProduct: `Frigidaire FFRA0511U1 Air`,image: '',summary: ``,slug: ""},
			B0779KHLXJ: {href: "https://amzn.to/3kCmc3A",nameProduct: `Marantz AV Receiver SR8012 - First-Ever High Performance 11.2 Channel`,image: '',summary: ``,slug: ""},
			B077N51CR2: {href: "https://amzn.to/3DcWg5H",nameProduct: `Homall Single Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B077PBGYVD: {href: "https://amzn.to/3DmTbQA",nameProduct: `Seatcraft Anthem Home Theater Seating`,image: '',summary: ``,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/3nfWSSm",nameProduct: `LUNA Adult Weighted Blanket Review`,image: '',summary: ``,slug: ""},
			B078964VVX: {href: "https://amzn.to/3oyqryh",nameProduct: `Westinghouse WGen7500DF Dual Fuel`,image: '',summary: ``,slug: ""},
			B078C6VHDD: {href: "https://amzn.to/2YMVa1D",nameProduct: `SVS PB-4000 Subwoofer `,image: '',summary: ``,slug: ""},
			B0792PD6TY: {href: "https://amzn.to/30tZ4gE",nameProduct: `Review Woodbridge b-0030/bts160`,image: '',summary: ``,slug: ""},
			B07983G4D4: {href: "https://amzn.to/3Flxr8p",nameProduct: `DynastyMattress DM9000s Split King Adjustable `,image: '',summary: ``,slug: ""},
			B079K4L5BD: {href: "https://amzn.to/3neGIbT",nameProduct: `ZINUS Ricardo Sofa Couch`,image: '',summary: ``,slug: ""},
			B079YW5VQL: {href: "https://amzn.to/3qDhzKn",nameProduct: `Sony STR-DH790 7.2-ch Surround Sound Home`,image: '',summary: ``,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/3ouo53d",nameProduct: `Nectar Mattress Review`,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/3wKfJbz",nameProduct: `SUPER DEAL Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07B9NP4GF: {href: "https://amzn.to/3DgRqo8",nameProduct: `Zinus Memory Foam 9 Inch BioFusion Mattress`,image: '',summary: ``,slug: ""},
			B07BKMSJ6X: {href: "https://amzn.to/3ceB0Ri",nameProduct: `REC TEC RT-700`,image: '',summary: ``,slug: ""},
			B07BN3B3YT: {href: "https://amzn.to/3qDhYfR",nameProduct: `Avanti STW20D2P portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07BNVST4P: {href: "https://amzn.to/3Cbe6Vm",nameProduct: `SWAGTRON Swagcycle EB5 Series Aluminum Folding Ebike `,image: '',summary: ``,slug: ""},
			B07C44DM6D: {href: "https://amzn.to/3ngqdML",nameProduct: `Dupray Neat Steam Cleaner`,image: '',summary: ``,slug: ""},
			B07C49F2LD: {href: "https://amzn.to/3qCdw0I",nameProduct: `Denon-AVR-S540BT-Receiver - Review 2021`,image: '',summary: ``,slug: ""},
			B07CHYKRK7: {href: "https://amzn.to/3kFuOWS",nameProduct: `COMFEE' Rice Cooker, Slow Cooker, Steamer, Stewpot, Sauté All in One`,image: '',summary: ``,slug: ""},
			B07CN38M23: {href: "https://amzn.to/3HmGkQG",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,image: '',summary: ``,slug: ""},
			B07CYGLK5G: {href: "https://amzn.to/3DdEb7w",nameProduct: `Yamaha P-125 Digital Piano Review`,image: '',summary: ``,slug: ""},
			B07CZ1CF79: {href: "https://amzn.to/3Hpic00",nameProduct: `Arctic Dreams 10" Hybrid Cooling Gel Mattress`,image: '',summary: ``,slug: ""},
			B07CZ5K355: {href: "https://amzn.to/30vcsRF",nameProduct: `Rachio 3 Smart Sprinkler Controller`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/3oxbFHJ",nameProduct: `YOSUDA Indoor Cycling Bike Stationary`,image: '',summary: ``,slug: ""},
			B07DFBQV15: {href: "https://amzn.to/3oAB8QW",nameProduct: `REL Acoustics HT1205 Subwoofer`,image: '',summary: ``,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/3CfnUOg",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner`,image: '',summary: ``,slug: ""},
			B07F39ZRCQ: {href: "https://amzn.to/3kBsLmK",nameProduct: `Bose Bass Module 700`,image: '',summary: ``,slug: ""},
			B07PSPLXND: {href: "https://amzn.to/3HmcADI",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Review `,image: '',summary: ``,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/3Ch00BK",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool`,image: '',summary: ``,slug: ""},
			B07F618LKC: {href: "https://amzn.to/3HpIqQ3",nameProduct: `COSTWAY Compact Laundry Dryer`,image: '',summary: ``,slug: ""},
			B07FDFP79J: {href: "https://amzn.to/3DdFdAq",nameProduct: `Ninja Foodi 9-in-1 Pressure Unboxing`,image: '',summary: ``,slug: ""},
			B07FKJHNZX: {href: "https://amzn.to/3DxfH9H",nameProduct: `Bestway 57266-19 Round Kids Inflatable Pool`,image: '',summary: ``,slug: ""},
			B07FP186CN: {href: "https://amzn.to/3DiyRQm",nameProduct: `TOTO Neorest NX1 Electronic Dual Flush Toilet`,image: '',summary: ``,slug: ""},
			B07FSYZVTZ: {href: "https://amzn.to/3orCk93",nameProduct: `SereneLife Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B07FX7Z3NL: {href: "https://amzn.to/3ne0hkP",nameProduct: `Shark Navigator Upright Vacuum`,image: '',summary: ``,slug: ""},
			B07FZ8S74R: {href: "https://amzn.to/3Djizqu",nameProduct: `Echo Dot (3rd Gen)`,image: '',summary: ``,slug: ""},
			B07GNDDNMW: {href: "https://amzn.to/3wKpg2e",nameProduct: `SIHOO Ergonomic Office Chair`,image: '',summary: ``,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/3Dh5Mok",nameProduct: `Flume Water Monitor Review`,image: '',summary: ``,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3qEDyk6",nameProduct: `Kahuna LM6800 Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07H1B3PY9: {href: "https://amzn.to/2YPIDdO",nameProduct: `Polk Audio Signa S2 Ultra-Slim TV Sound Bar`,image: '',summary: ``,slug: ""},
			B07H2CKPJV: {href: "https://amzn.to/3niPKF7",nameProduct: `Callaway Golf Men's Strata Complete Set`,image: '',summary: ``,slug: ""},
			B07F3DNQ4Q: {href: "https://amzn.to/3qA1TYh",nameProduct: `Intex 15ft x 42in Prism Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B07H781NMC: {href: "https://amzn.to/3Fe0cnm",nameProduct: `WOODBRIDGE T-0019 Cotton White toilet Review`,image: '',summary: ``,slug: ""},
			B07H7R6YTB: {href: "https://amzn.to/3chUsMI",nameProduct: `WOODBRIDGE B-0960S B0960S Smart Bidet seat Toilet`,image: '',summary: ``,slug: ""},
			B07HB7QBQ2: {href: "https://amzn.to/3ChXR8X",nameProduct: `NordicTrack T Series Treadmill`,image: '',summary: ``,slug: ""},
			B07HVSR8RF: {href: "https://amzn.to/3cg49LT",nameProduct: `SUPER DEAL Portable Compact Washing Machine`,image: '',summary: ``,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/3DhEqhP",nameProduct: `Review Nod by Tuft And Needle Mattress`,image: '',summary: ``,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/30q9v4h",nameProduct: `ZENY Portable Clothes Washing Machine`,image: '',summary: ``,slug: ""},
			B01N1GN306: {href: "https://amzn.to/3qDBF73",nameProduct: `NAKTO 26" City Adult Electric Bicycle`,image: '',summary: ``,slug: ""},
			B07K7YXCFD: {href: "https://amzn.to/30sXAmR",nameProduct: `Cangshan N1 Series Review`,image: '',summary: ``,slug: ""},
			B07KKFDM1M: {href: "https://amzn.to/3CivS9k",nameProduct: `Craftsman V60 Cordless Lawn Mower`,image: '',summary: ``,slug: ""},
			B07L1P4SPB: {href: "https://amzn.to/2YNFAmr",nameProduct: `Inofia Responsive Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B07L4ZQMDX: {href: "https://amzn.to/3nf0c08",nameProduct: `NOUHAUS Ergo3D Ergonomic Office Chair Review`,image: '',summary: ``,slug: ""},
			B07M8F5P7B: {href: "https://amzn.to/3wQv1M2",nameProduct: `Dyson V7 Allergy HEPA Cord-Free Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07M949RQS: {href: "https://amzn.to/3chWFI0",nameProduct: `Valencia Tuscany Home Theater Seating`,image: '',summary: ``,slug: ""},
			B07MCDL9N3: {href: "https://amzn.to/3Dn0fwA",nameProduct: `hOmeLabs Freestanding Commercial`,image: '',summary: ``,slug: ""},
			B07MKLJLY4: {href: "https://amzn.to/3oyBzex",nameProduct: `Seatcraft Pantheon Big & Tall Home`,image: '',summary: ``,slug: ""},
			B07MRG5F4J: {href: "https://amzn.to/3chXznS",nameProduct: `Cuisinart TOA-65 Digital Convection Toaster Oven Airfryer`,image: '',summary: ``,slug: ""},
			B07MXQQQZ5: {href: "https://amzn.to/30vhzkP",nameProduct: `Touchstone 80036 - Sideline Elite Electric Fireplace`,image: '',summary: ``,slug: ""},
			B07MY2H45K: {href: "https://amzn.to/30u5E6Q",nameProduct: `LINENSPA 3 Inch Gel Infused Memory Foam Mattress Topper`,image: '',summary: ``,slug: ""},
			B07N3Z9M7H: {href: "https://amzn.to/3wKy9ZE",nameProduct: `Keystone KSTAD50B Energy Star`,image: '',summary: ``,slug: ""},
			B097C8XB1R: {href: "https://amzn.to/3ngnnqT",nameProduct: `LG LP1419IVSM 14000 BTU Portable`,image: '',summary: ``,slug: ""},
			B07NRBDMJR: {href: "https://amzn.to/3CcECxv",nameProduct: `MIDEA MAD50C1ZWS Dehumidifier for up to 4500 Sq Ft`,image: '',summary: ``,slug: ""},
			B07PB37R7H: {href: "https://amzn.to/3cfDn6a",nameProduct: `Hbada Ergonomic Office Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B07PBFKXW9: {href: "https://amzn.to/3oxilFN",nameProduct: `Sony XB72 High Power Home Audio System`,image: '',summary: ``,slug: ""},
			B07PDXKSGJ: {href: "https://amzn.to/3cfgjV6",nameProduct: `MIDEA EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B07PL6LDP1: {href: "https://amzn.to/3c9He4S",nameProduct: `Sony HT-S350 Soundbar Review`,image: '',summary: ``,slug: ""},
			B07Q19RL7D: {href: "https://amzn.to/3DtZhOY",nameProduct: `Subrtex 3 Inch Gel-Infused Memory Foam Bed Mattress`,image: '',summary: ``,slug: ""},
			B07Q9MDWQH: {href: "https://amzn.to/3qE65Gn",nameProduct: `Hoover ONEPWR Blade+ Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07QLR12BV: {href: "https://amzn.to/3qEewBm",nameProduct: `Hbada Office Task Desk Chair Review`,image: '',summary: ``,slug: ""},
			B07QV8PMBY: {href: "https://amzn.to/3wLM7KR",nameProduct: `Massage Chair by OOTORI, Zero Gravity Massage Chair`,image: '',summary: ``,slug: ""},
			B07QX2BYDH: {href: "https://amzn.to/3cftW6J",nameProduct: `Amazon Basics Gaming Computer Desk`,image: '',summary: ``,slug: ""},
			B07QYC1TFB: {href: "https://amzn.to/31QV8H1",nameProduct: `Ohana 7-Piece Outdoor Furniture Review`,image: '',summary: ``,slug: ""},
			B07RCNHTLS: {href: "https://amzn.to/30tNORe",nameProduct: `Instant Pot Duo Nova 7-in-1 Electric Pressure Cooker`,image: '',summary: ``,slug: ""},
			B07RHQ5YNZ: {href: "https://amzn.to/3HmP1dM",nameProduct: `Frigidaire 12,000 BTU 115V Window`,image: '',summary: ``,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/3Dk5XPI",nameProduct: `WoodBridge T 0001 Review2020`,image: '',summary: ``,slug: ""},
			B07S2348R9: {href: "https://amzn.to/3qBzoJJ",nameProduct: `SUPER DEAL 2IN1 Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B07S39CW8Q: {href: "https://amzn.to/30oDHgT",nameProduct: `Giantex Full Automatic Washing Machine Portable`,image: '',summary: ``,slug: ""},
			B07S76WBGF: {href: "https://amzn.to/3kyA3rq",nameProduct: `Ninja Foodi 5-in-1 4-Qt`,image: '',summary: ``,slug: ""},
			B07SFJXLYW: {href: "https://amzn.to/3onSfoE",nameProduct: `SereneLife 12,000 BTU Portable 3 in 1 Air Conditioner for Rooms Up to 450 Sq. Ft`,image: '',summary: ``,slug: ""},
			B07SQ9YCJB: {href: "https://amzn.to/3HkXApF",nameProduct: `BLACK+DECKER Powerseries Cordless`,image: '',summary: ``,slug: ""},
			B07SS48CC7: {href: "https://amzn.to/3ne94mQ",nameProduct: `Hayward W3HP21404T Pool Heat Pump Review`,image: '',summary: ``,slug: ""},
			B07SV9516S: {href: "https://amzn.to/3CfmYZZ",nameProduct: `Hayward Pool Heater Review`,image: '',summary: ``,slug: ""},
			B07TC3659T: {href: "https://amzn.to/3Dh3wxy",nameProduct: `KUPPET Compact Twin Tub Portable Mini Washing`,image: '',summary: ``,slug: ""},
			B07TDHXBYT: {href: "https://amzn.to/3kXTMRN",nameProduct: `Atlantic Furniture Deerfield Murphy Bed Chest`,image: '',summary: ``,slug: ""},
			B07TDP2MMQ: {href: "https://amzn.to/3wNfdJQ",nameProduct: `KUPPET Compact Twin Tub Portable`,image: '',summary: ``,slug: ""},
			B07TGQZGGZ: {href: "https://amzn.to/30rSS8k",nameProduct: `NordicTrack Commercial Studio Cycle Review`,image: '',summary: ``,slug: ""},
			B07V48X7HG: {href: "https://amzn.to/2YNH2oJ",nameProduct: `Review LG LW1019IVSM Energy Star`,image: '',summary: ``,slug: ""},
			B07VC44C68: {href: "https://amzn.to/3Ddbwzv",nameProduct: `WORX WR150 Landroid L 20V Robotic Lawn Mower`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/3HobpDF",nameProduct: `Farberware FDW05ASBWHA Complete Portable Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B07VRWZCDS: {href: "https://amzn.to/3qEyVqi",nameProduct: `Sven and Son King Adjustable Bed Base Frame Platinum`,image: '',summary: ``,slug: ""},
			B07VVK39F7: {href: "https://amzn.to/3otgUZ1",nameProduct: `LEVOIT Air Purifier for Home Allergies Pets Hair Smokers in Bedroom`,image: '',summary: ``,slug: ""},
			B07W7G23ZG: {href: "https://amzn.to/3ngg6rf",nameProduct: `Ring Stick Up Cam Solar HD security camera`,image: '',summary: ``,slug: ""},
			B07XBPMBTF: {href: "https://amzn.to/3CmcwQp",nameProduct: `SGorri Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07XBYFS9Z: {href: "https://amzn.to/3Dph620",nameProduct: `Zero Gravity Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B07XKCMKWB: {href: "https://amzn.to/3DhRjs9",nameProduct: `JOOLA Inside - Professional MDF Indoor `,image: '',summary: ``,slug: ""},
			B07Y8BXBX8: {href: "https://amzn.to/3HnQdO1",nameProduct: `Gabrylly Ergonomic Mesh Office Chair Review`,image: '',summary: ``,slug: ""},
			B081DG1BRW: {href: "https://amzn.to/30lFWkv",nameProduct: `Portable Washing Machine KUPPET 16 5lbs`,image: '',summary: ``,slug: ""},
			B081RG8JYR: {href: "https://amzn.to/3ouDCA3",nameProduct: `Waykar 2000 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B082324K53: {href: "https://amzn.to/3qEPmmq",nameProduct: `Intex 6 Person Hot Tub Review`,image: '',summary: ``,slug: ""},
			B082LXF4VK: {href: "https://amzn.to/3qSRJ5h",nameProduct: `Intex PureSpa Greywood Deluxe 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B083G9WVNC: {href: "https://amzn.to/3CfrgAz",nameProduct: `Panda PAN6320W Portable Machine`,image: '',summary: ``,slug: ""},
			B083LL68Z5: {href: "https://amzn.to/3wJL1iM",nameProduct: `Intex Simple Spa Outdoor Portable Hot Tub`,image: '',summary: ``,slug: ""},
			B08XYNM7K2: {href: "https://amzn.to/3Hn6xik",nameProduct: `Homech Inflatable Swimming Pools`,image: '',summary: ``,slug: ""},
			B084P72GYX: {href: "https://amzn.to/3oxVB8C",nameProduct: `Fitness Reality Multi Function Adjustable Power Rack Squat Stand`,image: '',summary: ``,slug: ""},
			B085797ZFF: {href: "https://amzn.to/3qB4oJF",nameProduct: `MIDEA MAW05M1BWT Window air conditioner 5000 BTU`,image: '',summary: ``,slug: ""},
			B0861HFYW1: {href: "https://amzn.to/30oJCm7",nameProduct: `LUCID 10 Inch 2020 Gel Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B0866Y33PL: {href: "https://amzn.to/3CbsOM8",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B0867GMW9X: {href: "https://amzn.to/3nfZeAQ",nameProduct: `Midea U Inverter Window Air Conditioner 12,000BTU`,image: '',summary: ``,slug: ""},
			B086Q2M7FK: {href: "https://amzn.to/3cdh5SQ",nameProduct: `Rancilio Silvia M V6 Espresso Machine`,image: '',summary: ``,slug: ""},
			B087Q3PTJP: {href: "https://amzn.to/3wOCMlF",nameProduct: `Ugears Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B088T949GP: {href: "https://amzn.to/30rxX5D",nameProduct: `OOTORI RL900 Full Body Electric Massage Chair`,image: '',summary: ``,slug: ""},
			B089JS623C: {href: "https://amzn.to/3DktX5d",nameProduct: `Linenspa 12 Inch Memory Hybrid Plush Mattress`,image: '',summary: ``,slug: ""},
			B08BPJ76GP: {href: "https://amzn.to/3neTzee",nameProduct: `Frigidaire 50 Pint FFAD5033W1 Dehumidifier`,image: '',summary: ``,slug: ""},
			B08FKX9KMD: {href: "https://amzn.to/2YLxHh9",nameProduct: `Beginner Cycle Bike Workout With Sunny Health & Fitness Cycling Bike`,image: '',summary: ``,slug: ""},
			B08GH4NFDH: {href: "https://amzn.to/30ryXqp",nameProduct: `GoPlus Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B08GYL2CBM: {href: "https://amzn.to/30qUwaA",nameProduct: `Zinus 14 Inch Gel Memory Foam Pocket Spring Hybrid Mattress`,image: '',summary: ``,slug: ""},
			B08HN5WLMM: {href: "https://amzn.to/3HgqsiG",nameProduct: `OasisCraft Pre lit Snowy Aspen Spruce Christmas Tree`,image: '',summary: ``,slug: ""},
			B08HYXW1NL: {href: "https://amzn.to/3kCuSqA",nameProduct: `iRest SL Track Massage Chair Recliner, Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B08LG7GNMJ: {href: "https://amzn.to/3oo1iGk",nameProduct: `Ootori N503 Deluxe Massage Chair`,image: '',summary: ``,slug: ""},
			B08NSVXHB6: {href: "https://amzn.to/3Ddjw3v",nameProduct: `Essential Hot Tubs Polara Review`,image: '',summary: ``,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/3ngj7aO",nameProduct: `Essential Hot Tubs 67-Jet Syracuse Hot Tub`,image: '',summary: ``,slug: ""},
			MCSDRY15W: {href: "https://amzn.to/3wUc7Un",nameProduct: `Magic Chef Compact Electric White MCSDRY15W 1.5 cu`,image: '',summary: ``,slug: ""},
			B07H37YHMZ: {href: "https://amzn.to/324nb67",nameProduct: `Intex 15 Feet x 48 Inches Prism Frame Pool Set`,image: '',summary: ``,slug: ""},
			B07NH4LW1M: {href: "https://amzn.to/3nekln9",nameProduct: `Herman Miller Embody Chair`,image: '',summary: ``,slug: ""},
			b00euu5g82: {href: "https://amzn.to/3qJr0YN",nameProduct: `Serta AIR Health and Wellness Executive Office Chair`,image: '',summary: ``,slug: ""},
			b002kv1mju: {href: "https://amzn.to/3neWKma",nameProduct: `Marcy Recumbent Exercise Bike`,image: '',summary: ``,slug: ""},
			B01CK31J0Y: {href: "https://amzn.to/3CihoWP",nameProduct: `Hurtle Fitness Vibration Platform Machine`,image: '',summary: ``,slug: ""},
			b083fbnwcd: {href: "https://amzn.to/3HojWqb",nameProduct: `SIDIZ T50 Home Office Desk Chair`,image: '',summary: ``,slug: ""},
			b07rgm11l5: {href: "https://amzn.to/3DhpOz2",nameProduct: `Frigidaire 5,000 BTU 115V Window Air Conditioner`,image: '',summary: ``,slug: ""},
			b07jh7gs76: {href: "https://amzn.to/3njabSl",nameProduct: `Comfier Shiatsu Neck & Back Massager`,image: '',summary: ``,slug: ""},
			B07SRYBJ6L: {href: "https://amzn.to/3CjKbdw",nameProduct: `Cedric Office Chair`,image: '',summary: ``,slug: ""},
			B00MU26OKG: {href: "https://amzn.to/2YMsAgK",nameProduct: `Intex Swim Centre Family Lounge Pool`,image: '',summary: ``,slug: ""},
			B08B66KGC6: {href: "https://amzn.to/3DheMdi",nameProduct: `Kesnos 2500 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B0833NW6SN: {href: "https://amzn.to/30nYBNb",nameProduct: `Russell Hobbs 26051 Cordless Electric Kettle`,image: '',summary: ``,slug: ""},
			B003FSTA0U: {href: "https://amzn.to/3qADnGo",nameProduct: `Ultrasport F-Bike and F-Rider Fitness Bike Trainer`,image: '',summary: ``,slug: ""},
			B08Y87T92T: {href: "https://amzn.to/3qDySe1",nameProduct: `Yaheetech Black Office Chair `,image: '',summary: ``,slug: ""},
			B07K3PW65W: {href: "https://amzn.to/3FiIeQM",nameProduct: `Schwinn Koen Kids Bike`,image: '',summary: ``,slug: ""},
			B07K3PNJJS: {href: "https://amzn.to/3Hq8wCv",nameProduct: `Schwinn Elm Kids Bike`,image: '',summary: ``,slug: ""},
			B00E95K6LU: {href: "https://amzn.to/3DjEb66",nameProduct: `Schwinn Toddler Balance Bike`,image: '',summary: ``,slug: ""},
			B07PFYWP3G: {href: "https://amzn.to/3qFeauA",nameProduct: `Blissful Nights z4 Adjustable Bed Frame`,image: '',summary: ``,slug: ""},
			B07F3DNDL4: {href: "https://amzn.to/3nhNTQN",nameProduct: `Intex 10ft X 30in Prism Frame Pool Set`,image: '',summary: ``,slug: ""},
			B01N4I8FOY: {href: "https://amzn.to/3r2GLdq",nameProduct: `Fitness Reality Squat Rack Power Cage`,image: '',summary: ``,slug: ""},
			B08B61YJW4: {href: "https://amzn.to/2ZgU9is",nameProduct: `iRest 2021 Massage Chair`,image: '',summary: ``,slug: ""},
			B086DG8CN1: {href: "https://amzn.to/2ZpvUi9",nameProduct: `Valuxhome Electric Fireplace`,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
