function getData(){
	const keysw = "www.taquocthang.com";
	var keyAPI = (typeof keyhost != 'undefined') ? keyhost : document.location.host;
	var dataAMZ = {};
	if(keysw == keyAPI){
		dataAMZ = {
			B000058TJ3: {href: "https://amzn.to/2TqMEmp",nameProduct: `Intex Swim Center Family Inflatable Pool`,image: '',summary: ``,slug: ""},
			B00005RHPD: {href: "https://amzn.to/2UkEifZ",nameProduct: `Bosch 1617EVSPK Wood Router Tool Combo Kit`,image: '',summary: ``,slug: ""},
			B000092TT0: {href: "https://amzn.to/3dIoE4P",nameProduct: `Polk Audio PSW505 12" Powered`,image: '',summary: ``,slug: ""},
			B0000AMK5F: {href: "https://amzn.to/3AvhGu2",nameProduct: `BOSTITCH Coil Roofing Nailer`,image: '',summary: ``,slug: ""},
			B0002KVQBA: {href: "https://amzn.to/3hAge0I",nameProduct: `Polk Audio PSW10 10" Powered Subwoofer`,image: '',summary: ``,slug: ""},
			B000ANEPYO: {href: "https://amzn.to/2Tq5l9L",nameProduct: `Honeywell HFD-120-Q `,image: '',summary: ``,slug: ""},
			B000BO8AKW: {href: "https://amzn.to/3hBWx8u",nameProduct: `Butterfly Centrefold 25 Table Tennis Table`,image: '',summary: ``,slug: ""},
			B000GFPTQY: {href: "https://amzn.to/36f5UWu",nameProduct: `Bose Acoutimass 10 Series IV`,image: '',summary: ``,slug: ""},
			B000UXPFMU: {href: "https://amzn.to/2V8fHeP",nameProduct: `Pentair SuperFlo Pool Pump`,image: '',summary: ``,slug: ""},
			B001BMDFPS: {href: "https://amzn.to/3jGXEXl",nameProduct: `DuroMax XP4400E Generator`,image: '',summary: ``,slug: ""},
			B002635ODW: {href: "https://amzn.to/3qLoLSr",nameProduct: `EcoSmart ECO 27 Electric Tankless Water Heater`,image: '',summary: ``,slug: ""},
			B002G51BZU: {href: "https://amzn.to/368mszA",nameProduct: `Mr. Heater Portable Buddy Heater`,image: '',summary: ``,slug: ""},
			B002QAYJPO: {href: "https://amzn.to/2Vayd6t",nameProduct: `Honeywell Germ Free Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B002R8CPRY: {href: "https://amzn.to/3waNZeg",nameProduct: `Sunny Health and Fitness SF E905 Elliptical Machine Cross Trainer `,image: '',summary: ``,slug: ""},
			B002WKJ5ES: {href: "https://amzn.to/3jMFQKB",nameProduct: `Hayward Goldline AQR15 AquaRite Electronic Salt Chlorination System`,image: '',summary: ``,slug: ""},
			B003MANSNG: {href: "https://amzn.to/3AoLEj7",nameProduct: `National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B0043E6PLC: {href: "https://amzn.to/3qHNYNO",nameProduct: `BLACK+DECKER Countertop Convection Toaster Oven`,image: '',summary: ``,slug: ""},
			B00467H5YW: {href: "https://amzn.to/3hfvUaz",nameProduct: `Sunny Health & Fitness Exercise Cycling Bike`,image: '',summary: ``,slug: ""},
			B004PULVOK: {href: "https://amzn.to/3jOp51g",nameProduct: `Kohler K-3999-0 Highline Comfort Height `,image: '',summary: ``,slug: ""},
			B004QERFA4: {href: "https://amzn.to/3jGfwS5",nameProduct: `Kohler Santa Rosa Comfort Toilet Review`,image: '',summary: ``,slug: ""},
			B0052OX876: {href: "https://amzn.to/3qMYZND",nameProduct: `Lotos LTP5000D 50Amp Non-Touch Pilot Arc Plasma Cutter`,image: '',summary: ``,slug: ""},
			B0055P70MQ: {href: "https://amzn.to/3AsNYWb",nameProduct: `Technivorm Moccamaster 59616 KBG Coffee Brewer`,image: '',summary: ``,slug: ""},
			B005BPWN0O: {href: "https://amzn.to/3dJPSIi",nameProduct: `Husqvarna 125B Handheld Blower`,image: '',summary: ``,slug: ""},
			B006H1QYBA: {href: "https://amzn.to/3dHfCoP",nameProduct: `Steelcase Leap Chair`,image: '',summary: ``,slug: ""},
			B006IY89ZA: {href: "https://amzn.to/3qXkQSZ",nameProduct: `Modway Articulate Ergonomic Mesh Office Chair`,image: '',summary: ``,slug: ""},
			B007HIKQCK: {href: "https://amzn.to/3hbJCLD",nameProduct: `Bio Bidet Ultimate BB-600 Advanced Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B008DBRFBK: {href: "https://amzn.to/2Tyj4v6",nameProduct: `Bissell 3624 Spot Clean Professional`,image: '',summary: ``,slug: ""},
			B009IJ2LM4: {href: "https://amzn.to/3qMMHos",nameProduct: `TOTO Washlet s300e Electronic Bidet Toilet Seat`,image: '',summary: ``,slug: ""},
			B009IJ2N9U: {href: "https://amzn.to/2TyycIW",nameProduct: `TOTO Washlet s350e Review 2020`,image: '',summary: ``,slug: ""},
			B009SCPYN4: {href: "https://amzn.to/3AAVSgD",nameProduct: `Hudson Bay Spas 4 Person`,image: '',summary: ``,slug: ""},
			B009X43F38: {href: "https://amzn.to/2UVdxPt",nameProduct: `Hobart Handler 140 MIG Welder`,image: '',summary: ``,slug: ""},
			B00A8UPX0Y: {href: "https://amzn.to/3AtRiQU",nameProduct: `National Tree Company Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00AB24XIW: {href: "https://amzn.to/3wbEHhX",nameProduct: `Dri-Eaz LGR 7000XLi Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00AB25016: {href: "https://amzn.to/3wl7rVv",nameProduct: `Dri-Eaz F284 DefendAir HEPA 500 Air Purifier`,image: '',summary: ``,slug: ""},
			B00BUV305A: {href: "https://amzn.to/3jCWyvL",nameProduct: `Luraco i7 PLUS Medical Massage`,image: '',summary: ``,slug: ""},
			B00C03D01Q: {href: "https://amzn.to/3dJLXvk",nameProduct: `Flo by Moen Smart Water Shutoff `,image: '',summary: ``,slug: ""},
			B00CH9QWOU: {href: "https://amzn.to/3jHuveI",nameProduct: `Breville the Barista Express Espresso Machine`,image: '',summary: ``,slug: ""},
			B00CMREO0Q: {href: "https://amzn.to/3qKYTWR",nameProduct: `Touchstone 80001 Onyx Electric `,image: '',summary: ``,slug: ""},
			B00EPNDJ24: {href: "https://amzn.to/3yg2HC2",nameProduct: `Manitowoc Nugget Ice Machine`,image: '',summary: ``,slug: ""},
			B00EUU5GFK: {href: "https://amzn.to/3AnZWR4",nameProduct: `Serta Ergonomic Executive Office Chair Review`,image: '',summary: ``,slug: ""},
			B00F2CGXGG: {href: "https://amzn.to/3qJ6XaC",nameProduct: `Dewalt 10" DWE7491RS Table Saw with Rolling Stand Review`,image: '',summary: ``,slug: ""},
			B00FADLVAK: {href: "https://amzn.to/3jBL7V8",nameProduct: `Review National Tree Company lit Artificial Christmas Tree`,image: '',summary: ``,slug: ""},
			B00FH441AE: {href: "https://amzn.to/3dH06cJ",nameProduct: `Review 16 Piece Deluxe Edition Christmas Nativity Set`,image: '',summary: ``,slug: ""},
			B00FOUDF62: {href: "https://amzn.to/3jGYoM7",nameProduct: `TOTO MS992CUMFG#01 Neorest`,image: '',summary: ``,slug: ""},
			B00G00BT72: {href: "https://amzn.to/3dJMcGK",nameProduct: `McCulloch MC1375 Canister Steam Cleaner`,image: '',summary: ``,slug: ""},
			B00GBADAT6: {href: "https://amzn.to/3yoYHz4",nameProduct: `JOOLA NOVA Outdoor Table Tennis`,image: '',summary: ``,slug: ""},
			B00GJ1N5VA: {href: "https://amzn.to/2Tyjy4o",nameProduct: `JOOLA Rally TL - Professional `,image: '',summary: ``,slug: ""},
			B00GN96JFW: {href: "https://amzn.to/3xiCXVx",nameProduct: `Flash Furniture Eclipse Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B00H3DIT14: {href: "https://amzn.to/3ynoeJe",nameProduct: `DRI EAZ F413 Revolution LGR Portable Dehumidifier`,image: '',summary: ``,slug: ""},
			B00H3RI32U: {href: "https://amzn.to/3qKYXG5",nameProduct: `Touchstone 80004 - Sideline Electric Fireplace`,image: '',summary: ``,slug: ""},
			B00HRT863U: {href: "https://amzn.to/3qPibdJ",nameProduct: `Bestway SaluSpa Miami Inflatable Hot Tub`,image: '',summary: ``,slug: ""},
			B00HXGSBXC: {href: "https://amzn.to/3hh5RzQ",nameProduct: `RoyalBaby Kids Bike Boys Girls Freestyle Bicycle`,image: '',summary: ``,slug: ""},
			B00I0ZGOZM: {href: "https://amzn.to/2UXfD1i",nameProduct: `APEC Drinking Water`,image: '',summary: ``,slug: ""},
			B00IFHPVEU: {href: "https://amzn.to/2V7alR5",nameProduct: `Amazon Basics Leather-Padded Office Chair Review`,image: '',summary: ``,slug: ""},
			B00IWJOOU8: {href: "https://amzn.to/3dEnXd2",nameProduct: `Briggs & Stratton P3000 Power Smart Series Inverter Generator`,image: '',summary: ``,slug: ""},
			B00JGRBSS6: {href: "https://amzn.to/2SLU0QR",nameProduct: `Marcy 150-lb Multifunctional Home Gym Station`,image: '',summary: ``,slug: ""},
			B00JH98GR4: {href: "https://amzn.to/2TyyLm2",nameProduct: `Shark Navigator Lift-Away Deluxe NV360 Upright Vacuum`,image: '',summary: ``,slug: ""},
			B00JJ5I7GQ: {href: "https://amzn.to/2UXk9ge",nameProduct: `Polaris F9550 Robotic Pool`,image: '',summary: ``,slug: ""},
			B00KYB47JU: {href: "https://amzn.to/3yjf40g",nameProduct: `American Spas AM-630LM 5-Person 30-Jet Lounger Spa`,image: '',summary: ``,slug: ""},
			B00LFS0DMG: {href: "https://amzn.to/3hx4hsH",nameProduct: `Steelcase Amia Task Chair Review`,image: '',summary: ``,slug: ""},
			B00MYWQL96: {href: "https://amzn.to/3hw8WuJ",nameProduct: `Hessaire MC37M Portable Evaporative Cooler`,image: '',summary: ``,slug: ""},
			B00NB3P98G: {href: "https://amzn.to/3dHvFTA",nameProduct: `Coleman SaluSpa Inflatable Hot Tub Spa`,image: '',summary: ``,slug: ""},
			B00OX5B8CW: {href: "https://amzn.to/3whkLdM",nameProduct: `Intex 12' x 30'' Metal Frame Pool`,image: '',summary: ``,slug: ""},
			B00PKXWIPC: {href: "https://amzn.to/2V6bwjH",nameProduct: `Review Safavieh Hudson Shag Collection SGH281A Area Rug`,image: '',summary: ``,slug: ""},
			B00Q7EE928: {href: "https://amzn.to/3hvpy64",nameProduct: `Xspec 20 inch 7 Speed Folding Compact City Commuter Bike`,image: '',summary: ``,slug: ""},
			B00Q7EPSHI: {href: "https://amzn.to/3wdGtzb",nameProduct: `Zinus 12 Inch Green Tea Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B00Q7EPY04: {href: "https://amzn.to/3hlsYcN",nameProduct: `Zinus Memory Foam 12 Inch Green Tea Mattress Queen`,image: '',summary: ``,slug: ""},
			B00QBZ2BX2: {href: "https://amzn.to/2V7BTpq",nameProduct: `TUFT & NEEDLE Original Mattress`,image: '',summary: ``,slug: ""},
			B00R6AW5S2: {href: "https://amzn.to/3yoi4IW",nameProduct: `Makita EB7650TH 75.6 cc MM4 Backpack Blower`,image: '',summary: ``,slug: ""},
			B00R73DYJW: {href: "https://amzn.to/2Tq6v57",nameProduct: `PuraFlame Western Electric Fireplace Insert`,image: '',summary: ``,slug: ""},
			B00R9HVPBK: {href: "https://amzn.to/3AoMHzz",nameProduct: `DHP Emily Futon Sofa Bed`,image: '',summary: ``,slug: ""},
			B00SMNLF4M: {href: "https://amzn.to/3jIAi3A",nameProduct: `WEN 56200i Super Quiet 2000 Watt Portable Inverter Generator`,image: '',summary: ``,slug: ""},
			B00TVFO08S: {href: "https://amzn.to/3hB70B5",nameProduct: `Bose Acoustimass 6 Series V Home Theater Speaker System`,image: '',summary: ``,slug: ""},
			B00TVFO0B0: {href: "https://amzn.to/3hemLis",nameProduct: `Bose Acoustimass 10 series V`,image: '',summary: ``,slug: ""},
			B00UVAJU6O: {href: "https://amzn.to/3jIj7Pt",nameProduct: `Classic Brands Cool Ventilated Gel Memory Foam 10 Inch`,image: '',summary: ``,slug: ""},
			B00UWP07LK: {href: "https://amzn.to/2Up2XAc",nameProduct: `Frigidaire 70-Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B00W4DCHUC: {href: "https://amzn.to/3wek6tl",nameProduct: `Zinus Ibidun Upholstered Button Tufted Platform Bed`,image: '',summary: ``,slug: ""},
			B00WR1OTY8: {href: "https://amzn.to/3hCAaQF",nameProduct: `SVS Ultra Center Channel Loudspeaker`,image: '',summary: ``,slug: ""},
			B00Z4TSRFW: {href: "https://amzn.to/3hCAejn",nameProduct: `Jura 15068 IMPRESSA C65 Automatic Coffee Machine`,image: '',summary: ``,slug: ""},
			B0116W5B5O: {href: "https://amzn.to/3jIU9Qi",nameProduct: `Review La-Z-Boy Delano Big`,image: '',summary: ``,slug: ""},
			B011IH6MBO: {href: "https://amzn.to/3yqSyTj",nameProduct: `Bose Wave SoundTouch Music System IV Review`,image: '',summary: ``,slug: ""},
			B0128T2HQK: {href: "https://amzn.to/3xiWhlw",nameProduct: `SmartBidet SB 1000 Smart Electric Bidet Seat`,image: '',summary: ``,slug: ""},
			B012H0K93I: {href: "https://amzn.to/3jHOUjy",nameProduct: `Zinus 12 Inch Cloud Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B013I40R8E: {href: "https://amzn.to/36edkt3",nameProduct: `Breville BPR700BSS Fast Slow Pro Multi Function Cooker`,image: '',summary: ``,slug: ""},
			B013LIN5W2: {href: "https://amzn.to/3ArSSTt",nameProduct: `Polk Audio T50 Home Theater Floor Standing Tower Speaker`,image: '',summary: ``,slug: ""},
			B0165UFOGS: {href: "https://amzn.to/3ApLQ1y",nameProduct: `TOTO SW2014#01 A100 Electronic Bidet Toilet`,image: '',summary: ``,slug: ""},
			B016J0EITS: {href: "https://amzn.to/2V8h2Cn",nameProduct: `SureFire X300 Ultra Series LED WeaponLights`,image: '',summary: ``,slug: ""},
			B016OIF2JU: {href: "https://amzn.to/3hybzMD",nameProduct: `Steelcase Gesture Chair Review`,image: '',summary: ``,slug: ""},
			B0185F07GS: {href: "https://amzn.to/2TCEib7",nameProduct: `Review PORTER-CABLE 20V MAX 8-Tool Cordless Drill Combo Kit`,image: '',summary: ``,slug: ""},
			B0193V3DJ6: {href: "https://amzn.to/3ApM1de",nameProduct: `NordicTrack T Series Treadmill Review`,image: '',summary: ``,slug: ""},
			B01AA8WOAK: {href: "https://amzn.to/3yl5qKr",nameProduct: `Whynter Elite ARC 122DS 12,000 BTU`,image: '',summary: ``,slug: ""},
			B01ALBMIEI: {href: "https://amzn.to/2TyzbJ8",nameProduct: `Giantex Portable Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B01AWXC70U: {href: "https://amzn.to/3qJ5QId",nameProduct: `Intex Pure Spa 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B01B4XUQI2: {href: "https://amzn.to/3whxUTS",nameProduct: `Frigidaire 8000 BTU Window Air Conditioner `,image: '',summary: ``,slug: ""},
			B01BM659ZG: {href: "https://amzn.to/3dEoKL2",nameProduct: `Aprilaire Dehumidifier`,image: '',summary: ``,slug: ""},
			B01D3FOD0Q: {href: "https://amzn.to/3qPiHsb",nameProduct: `LG LW8016ER 8,000 BTU 115V Window Mounted `,image: '',summary: ``,slug: ""},
			B01D8DAYII: {href: "https://amzn.to/3htxvIO",nameProduct: `Winix 5500-2 Air Purifier`,image: '',summary: ``,slug: ""},
			B01DD6C4TC: {href: "https://amzn.to/3qS5S0j",nameProduct: `Mr. Heater MH18B Big Buddy Indoor Propane Heater`,image: '',summary: ``,slug: ""},
			B01DEWZUG4: {href: "https://amzn.to/3dGVenO",nameProduct: `Panasonic Microwave Oven NN-SN686S`,image: '',summary: ``,slug: ""},
			B01DTIC778: {href: "https://amzn.to/3xcRgei",nameProduct: `Sun Joe MJ401E-PRO Electric Lawn Mower`,image: '',summary: ``,slug: ""},
			B01DV3849Q: {href: "https://amzn.to/3AkfxB4",nameProduct: `Infinity IT-8500X3 3D Zero Gravity Massage Chair Review`,image: '',summary: ``,slug: ""},
			B01E0NP5HU: {href: "https://amzn.to/3ykwTMr",nameProduct: `Seatcraft Dynasty Home Theater Seating`,image: '',summary: ``,slug: ""},
			B01H4UICZ8: {href: "https://amzn.to/2Unhj3U",nameProduct: `Instep Bike Trailer`,image: '',summary: ``,slug: ""},
			B01H7F0RPI: {href: "https://amzn.to/3hx5bW7",nameProduct: `Schwinn LOOP folding bike`,image: '',summary: ``,slug: ""},
			B01ICHJIM8: {href: "https://amzn.to/2TBwQ03",nameProduct: `BestOffice Gaming Chair`,image: '',summary: ``,slug: ""},
			B01IENFJ14: {href: "https://amzn.to/3dDcGcM",nameProduct: `Dyson V8 Absolute Cordless Stick`,image: '',summary: ``,slug: ""},
			B01IRMBG7I: {href: "https://amzn.to/3xgX9XL",nameProduct: `Panda 3200 rpm Portable Spin Dryer Review`,image: '',summary: ``,slug: ""},
			B01J664WSY: {href: "https://amzn.to/3hhSkZ0",nameProduct: `Vornado VMH600 Whole Room Stainless Steel`,image: '',summary: ``,slug: ""},
			B01L1TFG66: {href: "https://amzn.to/3jDddPT",nameProduct: `Z Grills Wood Pellet Grill Smoker Review `,image: '',summary: ``,slug: ""},
			B01L9X99GC: {href: "https://amzn.to/3dH5cWp",nameProduct: `Best Choice Products 7.5ft Premium Spruce Artificial Holiday Christmas Tree`,image: '',summary: ``,slug: ""},
			B01LW3SOPE: {href: "https://amzn.to/3jOqZiq",nameProduct: `AlorAir Basement/Crawl Space Dehumidifiers`,image: '',summary: ``,slug: ""},
			B01LW76AKC: {href: "https://amzn.to/3AqbuDs",nameProduct: `Polk Audio MagniFi Mini Home Theater Surround Sound Bar`,image: '',summary: ``,slug: ""},
			B01M0L0D90: {href: "https://amzn.to/3qJhkvf",nameProduct: `XTERRA Fitness TR150 Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B01M24RKQY: {href: "https://amzn.to/3yjg0Sk",nameProduct: `Kahuna Massage Chair LM6800`,image: '',summary: ``,slug: ""},
			B01M716CC2: {href: "https://amzn.to/3dIURsR",nameProduct: `Braun Series 9 Electric Shaver`,image: '',summary: ``,slug: ""},
			B01M73WPQ7: {href: "https://amzn.to/3dGyrsk",nameProduct: `PuraFlame Alice 50 Inches Recessed Electric Fireplace Review`,image: '',summary: ``,slug: ""},
			B01M7M9NXX: {href: "https://amzn.to/3ArlzA8",nameProduct: `ZINUS Shalini Upholstered Platform Bed Frame`,image: '',summary: ``,slug: ""},
			B01MAVR8UW: {href: "https://amzn.to/3qMG0TB",nameProduct: `Upgraded Version Pyle Portable Washer `,image: '',summary: ``,slug: ""},
			B01MCUXSFD: {href: "https://amzn.to/3dISCWp",nameProduct: `SVS Dual PB16-Ultra Subwoofer`,image: '',summary: ``,slug: ""},
			B01MPX171W: {href: "https://amzn.to/3dHy3tn",nameProduct: `Braun Series 7 Electric Shaver Review`,image: '',summary: ``,slug: ""},
			B01MRZ02TL: {href: "https://amzn.to/2UnhBrw",nameProduct: `Homall Gaming Chair Office Chair`,image: '',summary: ``,slug: ""},
			B01MS22KO3: {href: "https://amzn.to/3hltDeh",nameProduct: `Human Touch Novo XT Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B01N0KXNFX: {href: "https://amzn.to/3jE6xAP",nameProduct: `Zinus 6 Inch Spring Twin Mattress Review`,image: '',summary: ``,slug: ""},
			B01N4RO2F4: {href: "https://amzn.to/3dCvDwj",nameProduct: `Schwinn Rascal Bike Pet Trailer`,image: '',summary: ``,slug: ""},
			B01NAUZJPE: {href: "https://amzn.to/3yjHNC6",nameProduct: `Rheem RTEX-13 Residential Tankless Water Heater Review`,image: '',summary: ``,slug: ""},
			B06W2GYD8Y: {href: "https://amzn.to/36jaXoN",nameProduct: `Real Relax 2020 Massage Chair`,image: '',summary: ``,slug: ""},
			B06W54K29J: {href: "https://amzn.to/3dJz3gH",nameProduct: `Levoit LV-PUR131 Air Purifier `,image: '',summary: ``,slug: ""},
			B06XKRWWSG: {href: "https://amzn.to/3hvYe7H",nameProduct: `Sony STR-DN1080 7.2-ch Surround Sound Home Theater AV Receiver`,image: '',summary: ``,slug: ""},
			B06XPGHMGF: {href: "https://amzn.to/3hBZaqS",nameProduct: `Seatcraft Omega Home Theater Seating Review`,image: '',summary: ``,slug: ""},
			B06Y49GJX4: {href: "https://amzn.to/3jE6KnB",nameProduct: `Summer Waves 10ft x 30in Quick Set Inflatable Above Ground Pool`,image: '',summary: ``,slug: ""},
			B07144LZ9V: {href: "https://amzn.to/368obVA",nameProduct: `Review Best Choice Portable`,image: '',summary: ``,slug: ""},
			B071D58ZY5: {href: "https://amzn.to/3yni5MY",nameProduct: `LEVOIT LV H132 Air Purifier Review`,image: '',summary: ``,slug: ""},
			B071FFSN22: {href: "https://amzn.to/3wi6DB1",nameProduct: `Milliard Diplomat Folding`,image: '',summary: ``,slug: ""},
			B071HP9PDR: {href: "https://amzn.to/3yiuZfl",nameProduct: `ALORAIR Commercial Water Damage Restoration Dehumidifier`,image: '',summary: ``,slug: ""},
			B072VLKC4P: {href: "https://amzn.to/3hty19I",nameProduct: `Ashley Furniture Yandel Power Lift Recliner`,image: '',summary: ``,slug: ""},
			B073FKF9B5: {href: "https://amzn.to/3AChuZY",nameProduct: `Intex 18ft X 52in Ultra Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B073FNDD9F: {href: "https://amzn.to/2TykUfu",nameProduct: `Intex 24ft X 12ft X 52in Ultra Frame Rectangular Pool Review`,image: '',summary: ``,slug: ""},
			B073VBWKJZ: {href: "https://amzn.to/2Tq7DWp",nameProduct: `hOmeLabs 70 Pint Dehumidifier`,image: '',summary: ``,slug: ""},
			B073W1R4XQ: {href: "https://amzn.to/3htyaKi",nameProduct: `Edifier R1850DB Active Bookshelf Speakers`,image: '',summary: ``,slug: ""},
			B073X8ZBRL: {href: "https://amzn.to/3ynfNNQ",nameProduct: `Leggett & Platt Adjustable Bed`,image: '',summary: ``,slug: ""},
			B073ZC16ZD: {href: "https://amzn.to/3jUxdh9",nameProduct: `Magic Chef White MCSTCW09W1 0.9 cu. ft. Compact Washer`,image: '',summary: ``,slug: ""},
			B0744CTXW8: {href: "https://amzn.to/3AoO80V",nameProduct: `Review Swiss Madison St. Tropez Toilet`,image: '',summary: ``,slug: ""},
			B074D6VDT1: {href: "https://amzn.to/368osrA",nameProduct: `National Tree 21 Foot Kingswood Fir Pencil Tree`,image: '',summary: ``,slug: ""},
			B074ML6THR: {href: "https://amzn.to/3AsQiMT",nameProduct: `Brondell Swash SE600 Bidet Toilet Seat Review`,image: '',summary: ``,slug: ""},
			B074MLZR3Y: {href: "https://amzn.to/3hbKYpH",nameProduct: `Brondell Swash SE400 Seat Review`,image: '',summary: ``,slug: ""},
			B074PYH768: {href: "https://amzn.to/3AAY3Rl",nameProduct: `hOmeLabs Compact Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B074R7GK8V: {href: "https://amzn.to/3AqNPCP",nameProduct: `COSTWAY Mini Washing Machine Review`,image: '',summary: ``,slug: ""},
			B074T9FRT7: {href: "https://amzn.to/3AueiiG",nameProduct: `Vornado VMH300 Whole Room Metal Heater`,image: '',summary: ``,slug: ""},
			B075FBJXZ7: {href: "https://amzn.to/3yqBpcr",nameProduct: `Zinus Suzanne Metal and Wood Platform Bed Review`,image: '',summary: ``,slug: ""},
			B076KKX4BC: {href: "https://amzn.to/3hwaNjb",nameProduct: `Xiaomi Mi Electric Scooter Review`,image: '',summary: ``,slug: ""},
			B076QLXHDH: {href: "https://amzn.to/3dITGJT",nameProduct: `Frigidaire FFRA0511U1 Air`,image: '',summary: ``,slug: ""},
			B076RTR86T: {href: "https://amzn.to/3dITJW5",nameProduct: `Direct Spa Model M 780D Hot Tub 7-Person 73-Jet Lounger Spa Review`,image: '',summary: ``,slug: ""},
			B0779KHLXJ: {href: "https://amzn.to/3yqBA7B",nameProduct: `Marantz AV Receiver SR8012 - First-Ever High Performance 11.2 Channel`,image: '',summary: ``,slug: ""},
			B077N51CR2: {href: "https://amzn.to/3htyusu",nameProduct: `Homall Single Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B077PBGYVD: {href: "https://amzn.to/3AChRnk",nameProduct: `Seatcraft Anthem Home Theater Seating`,image: '',summary: ``,slug: ""},
			B0787BVSTH: {href: "https://amzn.to/3AqO40H",nameProduct: `LUNA Adult Weighted Blanket Review`,image: '',summary: ``,slug: ""},
			B078964VVX: {href: "https://amzn.to/3dHWo2q",nameProduct: `Westinghouse WGen7500DF Dual Fuel`,image: '',summary: ``,slug: ""},
			B078C6VHDD: {href: "https://amzn.to/3wqj4Lf",nameProduct: `SVS PB-4000 Subwoofer `,image: '',summary: ``,slug: ""},
			B0792PD6TY: {href: "https://amzn.to/3dIrHdh",nameProduct: `Review Woodbridge b-0030/bts160`,image: '',summary: ``,slug: ""},
			B07983G4D4: {href: "https://amzn.to/3dJzFD1",nameProduct: `DynastyMattress DM9000s Split King Adjustable `,image: '',summary: ``,slug: ""},
			B079K4L5BD: {href: "https://amzn.to/3yjIFXo",nameProduct: `ZINUS Ricardo Sofa Couch`,image: '',summary: ``,slug: ""},
			B079YW5VQL: {href: "https://amzn.to/3yn7nq0",nameProduct: `Sony STR-DH790 7.2-ch Surround Sound Home`,image: '',summary: ``,slug: ""},
			B07B42DWWC: {href: "https://amzn.to/3jGiKoF",nameProduct: `Nectar Mattress Review`,image: '',summary: ``,slug: ""},
			B07B94ZR74: {href: "https://amzn.to/36dhbqs",nameProduct: `SUPER DEAL Portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07B9NP4GF: {href: "https://amzn.to/3jHAP60",nameProduct: `Zinus Memory Foam 9 Inch BioFusion Mattress`,image: '',summary: ``,slug: ""},
			B07BKMSJ6X: {href: "https://amzn.to/3hbVnSm",nameProduct: `REC TEC RT-700`,image: '',summary: ``,slug: ""},
			B07BN3B3YT: {href: "https://amzn.to/3dZYxH1",nameProduct: `Avanti STW20D2P portable Washing Machine`,image: '',summary: ``,slug: ""},
			B07BNVST4P: {href: "https://amzn.to/369C9q8",nameProduct: `SWAGTRON Swagcycle EB5 Series Aluminum Folding Ebike `,image: '',summary: ``,slug: ""},
			B07C44DM6D: {href: "https://amzn.to/3Avl2gC",nameProduct: `Dupray Neat Steam Cleaner`,image: '',summary: ``,slug: ""},
			B07C49F2LD: {href: "https://amzn.to/2TrPiby",nameProduct: `Denon-AVR-S540BT-Receiver - Review 2021`,image: '',summary: ``,slug: ""},
			B07CHYKRK7: {href: "https://amzn.to/3AqZu4q",nameProduct: `COMFEE' Rice Cooker, Slow Cooker, Steamer, Stewpot, Sauté All in One`,image: '',summary: ``,slug: ""},
			B07CN38M23: {href: "https://amzn.to/3dGqweG",nameProduct: `Masterbuilt MB20071117 Digital Electric Smoker`,image: '',summary: ``,slug: ""},
			B07CYGLK5G: {href: "https://amzn.to/3jGkJcF",nameProduct: `Yamaha P-125 Digital Piano Review`,image: '',summary: ``,slug: ""},
			B07CZ1CF79: {href: "https://amzn.to/3yjIZp4",nameProduct: `Arctic Dreams 10" Hybrid Cooling Gel Mattress`,image: '',summary: ``,slug: ""},
			B07CZ5K355: {href: "https://amzn.to/3dGzUyQ",nameProduct: `Rachio 3 Smart Sprinkler Controller`,image: '',summary: ``,slug: ""},
			B07D528W98: {href: "https://amzn.to/3dHiDWb",nameProduct: `YOSUDA Indoor Cycling Bike Stationary`,image: '',summary: ``,slug: ""},
			B07DFBQV15: {href: "https://amzn.to/3qSLDje",nameProduct: `REL Acoustics HT1205 Subwoofer`,image: '',summary: ``,slug: ""},
			B07DTKXTXV: {href: "https://amzn.to/2Tym0rC",nameProduct: `Hoover Smartwash Automatic Carpet Cleaner`,image: '',summary: ``,slug: ""},
			B07F39ZRCQ: {href: "https://amzn.to/2V6edBP",nameProduct: `Bose Bass Module 700`,image: '',summary: ``,slug: ""},
			B07F3DP48S: {href: "https://amzn.to/3dZYU4n",nameProduct: `Intex 18ft X 52in Ultra XTR Pool Review `,image: '',summary: ``,slug: ""},
			B07F3QF4KX: {href: "https://amzn.to/3AtijUQ",nameProduct: `Intex 18ft X 9ft X 52in Ultra XTR Rectangular Pool`,image: '',summary: ``,slug: ""},
			B07F618LKC: {href: "https://amzn.to/3xhnJjI",nameProduct: `COSTWAY Compact Laundry Dryer`,image: '',summary: ``,slug: ""},
			B07FDFP79J: {href: "https://amzn.to/3yruCiJ",nameProduct: `Ninja Foodi 9-in-1 Pressure Unboxing`,image: '',summary: ``,slug: ""},
			B07FKJHNZX: {href: "https://amzn.to/3jUy7Kz",nameProduct: `Bestway 57266-19 Round Kids Inflatable Pool`,image: '',summary: ``,slug: ""},
			B07FP186CN: {href: "https://amzn.to/2V7EgZm",nameProduct: `TOTO Neorest NX1 Electronic Dual Flush Toilet`,image: '',summary: ``,slug: ""},
			B07FX7Z3NL: {href: "https://amzn.to/3dJOWE2",nameProduct: `Shark Navigator Upright Vacuum`,image: '',summary: ``,slug: ""},
			B07FZ8S74R: {href: "https://amzn.to/2V8j4lZ",nameProduct: `Echo Dot (3rd Gen)`,image: '',summary: ``,slug: ""},
			B07GNDDNMW: {href: "https://amzn.to/3hAyZ3Y",nameProduct: `SIHOO Ergonomic Office Chair`,image: '',summary: ``,slug: ""},
			B07GPXKN8Z: {href: "https://amzn.to/3jFjuKG",nameProduct: `Flume Water Monitor Review`,image: '',summary: ``,slug: ""},
			B07GXZ49DY: {href: "https://amzn.to/3jBNUO6",nameProduct: `Kahuna LM6800 Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07H1B3PY9: {href: "https://amzn.to/3dHX6N8",nameProduct: `Polk Audio Signa S2 Ultra-Slim TV Sound Bar`,image: '',summary: ``,slug: ""},
			B07H2CKPJV: {href: "https://amzn.to/3dGAPzf",nameProduct: `Callaway Golf Men's Strata Complete Set`,image: '',summary: ``,slug: ""},
			B07H2NP7PR: {href: "https://amzn.to/2Uk7QKI",nameProduct: `Intex 15ft x 42in Prism Frame Pool Set Review`,image: '',summary: ``,slug: ""},
			B07H781NMC: {href: "https://amzn.to/3xjJHm5",nameProduct: `WOODBRIDGE T-0019 Cotton White toilet Review`,image: '',summary: ``,slug: ""},
			B07H7R6YTB: {href: "https://amzn.to/3qN15gt",nameProduct: `WOODBRIDGE B-0960S B0960S Smart Bidet seat Toilet`,image: '',summary: ``,slug: ""},
			B07HB7QBQ2: {href: "https://amzn.to/3ylIYB8",nameProduct: `NordicTrack T Series Treadmill`,image: '',summary: ``,slug: ""},
			B07HVSR8RF: {href: "https://amzn.to/3dGXaN6",nameProduct: `SUPER DEAL Portable Compact Washing Machine`,image: '',summary: ``,slug: ""},
			B07J31T4NC: {href: "https://amzn.to/2V8jclt",nameProduct: `Review Nod by Tuft And Needle Mattress`,image: '',summary: ``,slug: ""},
			B07J6S4RZ9: {href: "https://amzn.to/3hAkwVS",nameProduct: `ZENY Portable Clothes Washing Machine`,image: '',summary: ``,slug: ""},
			B07JGRJHV1: {href: "https://amzn.to/3jFjKcC",nameProduct: `NAKTO 26" City Adult Electric Bicycle`,image: '',summary: ``,slug: ""},
			B07K7YXCFD: {href: "https://amzn.to/3qN1bVn",nameProduct: `Cangshan N1 Series Review`,image: '',summary: ``,slug: ""},
			B07KKFDM1M: {href: "https://amzn.to/36bZKGF",nameProduct: `Craftsman V60 Cordless Lawn Mower`,image: '',summary: ``,slug: ""},
			B07L1P4SPB: {href: "https://amzn.to/2TqQV9r",nameProduct: `Inofia Responsive Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B07L4ZQMDX: {href: "https://amzn.to/3jDyj0s",nameProduct: `NOUHAUS Ergo3D Ergonomic Office Chair Review`,image: '',summary: ``,slug: ""},
			B07M8F5P7B: {href: "https://amzn.to/3hfB2vp",nameProduct: `Dyson V7 Allergy HEPA Cord-Free Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07M949RQS: {href: "https://amzn.to/3hgqiNn",nameProduct: `Valencia Tuscany Home Theater Seating`,image: '',summary: ``,slug: ""},
			B07MCDL9N3: {href: "https://amzn.to/3jBOqf0",nameProduct: `hOmeLabs Freestanding Commercial`,image: '',summary: ``,slug: ""},
			B07MKLJLY4: {href: "https://amzn.to/3jHkaPK",nameProduct: `Seatcraft Pantheon Big & Tall Home`,image: '',summary: ``,slug: ""},
			B07MRG5F4J: {href: "https://amzn.to/3ymmtff",nameProduct: `Cuisinart TOA-65 Digital Convection Toaster Oven Airfryer`,image: '',summary: ``,slug: ""},
			B07MXQQQZ5: {href: "https://amzn.to/3AtqD6Q",nameProduct: `Touchstone 80036 - Sideline Elite Electric Fireplace`,image: '',summary: ``,slug: ""},
			B07MY2H45K: {href: "https://amzn.to/2TxxP1f",nameProduct: `LINENSPA 3 Inch Gel Infused Memory Foam Mattress Topper`,image: '',summary: ``,slug: ""},
			B07N3Z9M7H: {href: "https://amzn.to/2TrQdJ2",nameProduct: `Keystone KSTAD50B Energy Star`,image: '',summary: ``,slug: ""},
			B07NRBDMJR: {href: "https://amzn.to/2UoeZJQ",nameProduct: `MIDEA MAD50C1ZWS Dehumidifier for up to 4500 Sq Ft`,image: '',summary: ``,slug: ""},
			B07PB37R7H: {href: "https://amzn.to/3AsRD6n",nameProduct: `Hbada Ergonomic Office Recliner Chair Review`,image: '',summary: ``,slug: ""},
			B07PBFKXW9: {href: "https://amzn.to/3jDfJWl",nameProduct: `Sony XB72 High Power Home Audio System`,image: '',summary: ``,slug: ""},
			B07PDXKSGJ: {href: "https://amzn.to/3xjsjxI",nameProduct: `MIDEA EasyCool Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B07PL6LDP1: {href: "https://amzn.to/3dJAJH1",nameProduct: `Sony HT-S350 Soundbar Review`,image: '',summary: ``,slug: ""},
			B07Q19RL7D: {href: "https://amzn.to/2SJOFJO",nameProduct: `Subrtex 3 Inch Gel-Infused Memory Foam Bed Mattress`,image: '',summary: ``,slug: ""},
			B07Q9MDWQH: {href: "https://amzn.to/3hBZW7m",nameProduct: `Hoover ONEPWR Blade+ Cordless Stick Vacuum Cleaner`,image: '',summary: ``,slug: ""},
			B07QLR12BV: {href: "https://amzn.to/2SLWaQt",nameProduct: `Hbada Office Task Desk Chair Review`,image: '',summary: ``,slug: ""},
			B07QV8PMBY: {href: "https://amzn.to/2TCH545",nameProduct: `Massage Chair by OOTORI, Zero Gravity Massage Chair`,image: '',summary: ``,slug: ""},
			B07QX2BYDH: {href: "https://amzn.to/3waZRgg",nameProduct: `Amazon Basics Gaming Computer Desk`,image: '',summary: ``,slug: ""},
			B07QYC1TFB: {href: "https://amzn.to/2UVhgwr",nameProduct: `Ohana 7-Piece Outdoor Furniture Review`,image: '',summary: ``,slug: ""},
			B07RCNHTLS: {href: "https://amzn.to/3ACjj9g",nameProduct: `Instant Pot Duo Nova 7-in-1 Electric Pressure Cooker`,image: '',summary: ``,slug: ""},
			B07RHQ5YNZ: {href: "https://amzn.to/3ApD3wH",nameProduct: `Frigidaire 12,000 BTU 115V Window`,image: '',summary: ``,slug: ""},
			B07RRF95QW: {href: "https://amzn.to/3xmeyys",nameProduct: `EuroMini Zizzo CAMPO Folding Bike Review`,image: '',summary: ``,slug: ""},
			B07RSM91SY: {href: "https://amzn.to/3yg6DTk",nameProduct: `WoodBridge T 0001 Review2020`,image: '',summary: ``,slug: ""},
			B07S2348R9: {href: "https://amzn.to/3ylJsHs",nameProduct: `SUPER DEAL 2IN1 Mini Compact Twin Tub Washing Machine`,image: '',summary: ``,slug: ""},
			B07S39CW8Q: {href: "https://amzn.to/3AAZFKT",nameProduct: `Giantex Full Automatic Washing Machine Portable`,image: '',summary: ``,slug: ""},
			B07S76WBGF: {href: "https://amzn.to/3ApOLaw",nameProduct: `Ninja Foodi 5-in-1 4-Qt`,image: '',summary: ``,slug: ""},
			B07SFJXLYW: {href: "https://amzn.to/3wi81DJ",nameProduct: `SereneLife 12,000 BTU Portable 3 in 1 Air Conditioner for Rooms Up to 450 Sq. Ft`,image: '',summary: ``,slug: ""},
			B07SG4KNT4: {href: "https://amzn.to/2TBzyTh",nameProduct: `Deik Cordless Stick Vacuum Review`,image: '',summary: ``,slug: ""},
			B07SQ9YCJB: {href: "https://amzn.to/3xkvuVW",nameProduct: `BLACK+DECKER Powerseries Cordless`,image: '',summary: ``,slug: ""},
			B07SS48CC7: {href: "https://amzn.to/3hxT0rX",nameProduct: `Hayward W3HP21404T Pool Heat Pump Review`,image: '',summary: ``,slug: ""},
			B07SV9516S: {href: "https://amzn.to/3hxzY54",nameProduct: `Hayward Pool Heater Review`,image: '',summary: ``,slug: ""},
			B07TC3659T: {href: "https://amzn.to/3ArlcFD",nameProduct: `KUPPET Compact Twin Tub Portable Mini Washing`,image: '',summary: ``,slug: ""},
			B07TDHXBYT: {href: "https://amzn.to/3xiFejx",nameProduct: `Atlantic Furniture Deerfield Murphy Bed Chest`,image: '',summary: ``,slug: ""},
			B07TDP2MMQ: {href: "https://amzn.to/3hdJMC7",nameProduct: `KUPPET Compact Twin Tub Portable`,image: '',summary: ``,slug: ""},
			B07TGQZGGZ: {href: "https://amzn.to/3dF5KMe",nameProduct: `NordicTrack Commercial Studio Cycle Review`,image: '',summary: ``,slug: ""},
			B07V48X7HG: {href: "https://amzn.to/3hwcJYZ",nameProduct: `Review LG LW1019IVSM Energy Star`,image: '',summary: ``,slug: ""},
			B07VC44C68: {href: "https://amzn.to/3jHyyHW",nameProduct: `WORX WR150 Landroid L 20V Robotic Lawn Mower`,image: '',summary: ``,slug: ""},
			B07VR22832: {href: "https://amzn.to/2UofiV0",nameProduct: `Farberware FDW05ASBWHA Complete Portable Countertop Dishwasher`,image: '',summary: ``,slug: ""},
			B07VRWZCDS: {href: "https://amzn.to/3hyePYn",nameProduct: `Sven and Son King Adjustable Bed Base Frame Platinum`,image: '',summary: ``,slug: ""},
			B07VVK39F7: {href: "https://amzn.to/36biAxB",nameProduct: `LEVOIT Air Purifier for Home Allergies Pets Hair Smokers in Bedroom`,image: '',summary: ``,slug: ""},
			B07W7G23ZG: {href: "https://amzn.to/3AqEUBb",nameProduct: `Ring Stick Up Cam Solar HD security camera`,image: '',summary: ``,slug: ""},
			B07XBPMBTF: {href: "https://amzn.to/3ykQBHR",nameProduct: `SGorri Massage Chair Review`,image: '',summary: ``,slug: ""},
			B07XBYFS9Z: {href: "https://amzn.to/3ApPf0k",nameProduct: `Zero Gravity Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B07XKCMKWB: {href: "https://amzn.to/3ApPfxm",nameProduct: `JOOLA Inside - Professional MDF Indoor `,image: '',summary: ``,slug: ""},
			B07Y8BXBX8: {href: "https://amzn.to/3yA1Exd",nameProduct: `Gabrylly Ergonomic Mesh Office Chair Review`,image: '',summary: ``,slug: ""},
			B081DG1BRW: {href: "https://amzn.to/3jIXUoS",nameProduct: `Portable Washing Machine KUPPET 16 5lbs`,image: '',summary: ``,slug: ""},
			B081RG8JYR: {href: "https://amzn.to/3dG2ikH",nameProduct: `Waykar 2000 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B082324K53: {href: "https://amzn.to/2TBA0kr",nameProduct: `Intex 6 Person Hot Tub Review`,image: '',summary: ``,slug: ""},
			B082LXF4VK: {href: "https://amzn.to/2SOxKWE",nameProduct: `Intex PureSpa Greywood Deluxe 6 Person Hot Tub`,image: '',summary: ``,slug: ""},
			B083G9WVNC: {href: "https://amzn.to/3hxTo9T",nameProduct: `Panda PAN6320W Portable Machine`,image: '',summary: ``,slug: ""},
			B083LL68Z5: {href: "https://amzn.to/3yiVyks",nameProduct: `Intex Simple Spa Outdoor Portable Hot Tub`,image: '',summary: ``,slug: ""},
			B084DBC9MN: {href: "https://amzn.to/3yni5MW",nameProduct: `Danby DDR050BJWDB 50 Pint Energy Star Dehumidifier`,image: '',summary: ``,slug: ""},
			B084P72GYX: {href: "https://amzn.to/2SOxQO0",nameProduct: `Fitness Reality Multi Function Adjustable Power Rack Squat Stand`,image: '',summary: ``,slug: ""},
			B085797ZFF: {href: "https://amzn.to/3yolLOO",nameProduct: `MIDEA MAW05M1BWT Window air conditioner 5000 BTU`,image: '',summary: ``,slug: ""},
			B0861HFYW1: {href: "https://amzn.to/3yqW0gJ",nameProduct: `LUCID 10 Inch 2020 Gel Memory Foam Mattress`,image: '',summary: ``,slug: ""},
			B0866Y33PL: {href: "https://amzn.to/3yg7hjI",nameProduct: `Midea U Inverter Window Air Conditioner`,image: '',summary: ``,slug: ""},
			B0867GMW9X: {href: "https://amzn.to/3jOtP74",nameProduct: `Midea U Inverter Window Air Conditioner 12,000BTU`,image: '',summary: ``,slug: ""},
			B086Q2M7FK: {href: "https://amzn.to/3jGmF4V",nameProduct: `Rancilio Silvia M V6 Espresso Machine`,image: '',summary: ``,slug: ""},
			B087Q3PTJP: {href: "https://amzn.to/3hBaqDV",nameProduct: `Ugears Massage Chair Review 2020`,image: '',summary: ``,slug: ""},
			B088T949GP: {href: "https://amzn.to/3dCyDJ5",nameProduct: `OOTORI RL900 Full Body Electric Massage Chair`,image: '',summary: ``,slug: ""},
			B0894K616X: {href: "https://amzn.to/3ArlCfb",nameProduct: `Dahon Mariner D8 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B0897Q7VH2: {href: "https://amzn.to/3dHBjF7",nameProduct: `Dahon Dream D6 Folding Bike Review`,image: '',summary: ``,slug: ""},
			B089JS623C: {href: "https://amzn.to/3hCGcRd",nameProduct: `Linenspa 12 Inch Memory Hybrid Plush Mattress`,image: '',summary: ``,slug: ""},
			B08BPJ76GP: {href: "https://amzn.to/2TyCVdE",nameProduct: `Frigidaire 50 Pint FFAD5033W1 Dehumidifier`,image: '',summary: ``,slug: ""},
			B08FKX9KMD: {href: "https://amzn.to/3AsSuUD",nameProduct: `Beginner Cycle Bike Workout With Sunny Health & Fitness Cycling Bike`,image: '',summary: ``,slug: ""},
			B08GH4NFDH: {href: "https://amzn.to/3ynkZkQ",nameProduct: `GoPlus Folding Treadmill Review`,image: '',summary: ``,slug: ""},
			B08GYL2CBM: {href: "https://amzn.to/3qMHTj9",nameProduct: `Zinus 14 Inch Gel Memory Foam Pocket Spring Hybrid Mattress`,image: '',summary: ``,slug: ""},
			B08HN5WLMM: {href: "https://amzn.to/3ArWwwD",nameProduct: `OasisCraft Pre lit Snowy Aspen Spruce Christmas Tree`,image: '',summary: ``,slug: ""},
			B08HYXW1NL: {href: "https://amzn.to/3ylKnYq",nameProduct: `iRest SL Track Massage Chair Recliner, Full Body Massage Chair`,image: '',summary: ``,slug: ""},
			B08LG7GNMJ: {href: "https://amzn.to/3dJBOP5",nameProduct: `Ootori N503 Deluxe Massage Chair`,image: '',summary: ``,slug: ""},
			B08LK72YV3: {href: "https://amzn.to/3ykeVcN",nameProduct: `Dahon Launch D8 Review`,image: '',summary: ``,slug: ""},
			B08NSVXHB6: {href: "https://amzn.to/3xtFzzS",nameProduct: `Essential Hot Tubs Polara Review`,image: '',summary: ``,slug: ""},
			B08NT4YBQ3: {href: "https://amzn.to/2UrwTf6",nameProduct: `Essential Hot Tubs 67-Jet Syracuse Hot Tub`,image: '',summary: ``,slug: ""},
			B08WYYNXKQ: {href: "https://amzn.to/3qJ1JvA",nameProduct: `ECOTRIC Fat Tire Electric Bike Beach Snow Bicycle`,image: '',summary: ``,slug: ""},
			MCSDRY15W: {href: "https://amzn.to/3waRzFe",nameProduct: `Magic Chef Compact Electric White MCSDRY15W 1.5 cu`,image: '',summary: ``,slug: ""},
			B07H37YHMZ: {href: "https://amzn.to/3hxTQ85",nameProduct: `Intex 15 Feet x 48 Inches Prism Frame Pool Set`,image: '',summary: ``,slug: ""},
			B07NH4LW1M: {href: "https://amzn.to/3hBaGCT",nameProduct: `Herman Miller Embody Chair`,image: '',summary: ``,slug: ""},
			b00euu5g82: {href: "https://amzn.to/3AtHner",nameProduct: `Serta AIR Health and Wellness Executive Office Chair`,image: '',summary: ``,slug: ""},
			b002kv1mju: {href: "https://amzn.to/3xg4jMc",nameProduct: `Marcy Recumbent Exercise Bike`,image: '',summary: ``,slug: ""},
			b07n41d7qy: {href: "https://amzn.to/3jBPYWm",nameProduct: `Hurtle Fitness Vibration Platform Machine`,image: '',summary: ``,slug: ""},
			b01ck31j0y: {href: "https://amzn.to/2TxzbsR",nameProduct: `Hurtle Fitness Vibration Platform Workout Machine`,image: '',summary: ``,slug: ""},
			b07bktdt3f: {href: "https://amzn.to/2VaDYB7",nameProduct: `SIHOO Office Chair`,image: '',summary: ``,slug: ""},
			b083fbnwcd: {href: "https://amzn.to/2Tzbf8r",nameProduct: `SIDIZ T50 Home Office Desk Chair`,image: '',summary: ``,slug: ""},
			b07rgm11l5: {href: "https://amzn.to/3dDg3QY",nameProduct: `Frigidaire 5,000 BTU 115V Window Air Conditioner`,image: '',summary: ``,slug: ""},
			b07jh7gs76: {href: "https://amzn.to/3dGBUXS",nameProduct: `Comfier Shiatsu Neck & Back Massager`,image: '',summary: ``,slug: ""},
			b07r62j6cr: {href: "https://amzn.to/3dHl6jp",nameProduct: `Herman Miller Embody Chair`,image: '',summary: ``,slug: ""},
			B07SRYBJ6L: {href: "https://amzn.to/3xkOK5Y",nameProduct: `Cedric Office Chair`,image: '',summary: ``,slug: ""},
			B00MU26OKG: {href: "https://amzn.to/3jHzs7i",nameProduct: `Intex Swim Centre Family Lounge Pool`,image: '',summary: ``,slug: ""},
			B08B66KGC6: {href: "https://amzn.to/3AqFXRD",nameProduct: `Kesnos 2500 Sq. Ft Dehumidifier`,image: '',summary: ``,slug: ""},
			B0833NW6SN: {href: "https://amzn.to/3AoRr8l",nameProduct: `Russell Hobbs 26051 Cordless Electric Kettle`,image: '',summary: ``,slug: ""},
			B08CDWG8LY: {href: "https://amzn.to/36gVy8s",nameProduct: `Homasy ColorMist Cool Mist Humidifier`,image: '',summary: ``,slug: ""},
			B07Z79VCMQ: {href: "https://amzn.to/2TrRDDm",nameProduct: `Fnova Exercise Bike Indoor Cycling`,image: '',summary: ``,slug: ""},
			B003FSTA0U: {href: "https://amzn.to/3ACkXYu",nameProduct: `Ultrasport F-Bike and F-Rider Fitness Bike Trainer`,image: '',summary: ``,slug: ""},
			B08Y87T92T: {href: "https://amzn.to/3hAAOhk",nameProduct: `Yaheetech Black Office Chair `,image: '',summary: ``,slug: ""},
			B07K3G7JBM: {href: "https://amzn.to/2V5sWwS",nameProduct: `Schwinn Koen Kids Bike`,image: '',summary: ``,slug: ""},
			B07K3PNJJS: {href: "https://amzn.to/3dIue7h",nameProduct: `Schwinn Elm Kids Bike`,image: '',summary: ``,slug: ""},
			B00E95K6LU: {href: "https://amzn.to/3yiWnK4",nameProduct: `Schwinn Toddler Balance Bike`,image: '',summary: ``,slug: ""}
		}
	}
	return dataAMZ;
}
